PROTOCCALLSFSUB1(GZEBRA,gzebra,INT)
#define GZEBRA(A1) CCALLSFSUB1(GZEBRA,gzebra,INT,A1)

PROTOCCALLSFSUB1(KUINIT,kuinit,INT)
#define KUINIT(A1) CCALLSFSUB1(KUINIT,kuinit,INT,A1)

PROTOCCALLSFSUB1(KUEXEL,kuexel,STRING)
#define KUEXEL(A1) CCALLSFSUB1(KUEXEL,kuexel,STRING,A1)

PROTOCCALLSFSUB0(GZINIT,gzinit)
#define GZINIT() CCALLSFSUB0(GZINIT,gzinit)

PROTOCCALLSFSUB0(VECDEF,vecdef)
#define VECDEF() CCALLSFSUB0(VECDEF,vecdef)

PROTOCCALLSFSUB9(MZSTOR,mzstor,PINT,STRING,STRING,PINT,PINT,PINT,PINT,PINT,PINT)
#define MZSTOR(A1,A2,A3,A4,A5,A6,A7,A8,A9) \
  CCALLSFSUB9(MZSTOR,mzstor,PINT,STRING,STRING,PINT,PINT,PINT,PINT,PINT,PINT,A1,A2,A3,A4,A5,A6,A7,A8,A9) 

PROTOCCALLSFSUB2(MZLOGL,mzlogl,INT,INT)
#define MZLOGL(A1,A2) CCALLSFSUB2(MZLOGL,mzlogl,INT,INT,A1,A2)

PROTOCCALLSFSUB6(MZDIV,mzdiv,INT,PINT,STRING,INT,INT,STRING)
#define MZDIV(A1,A2,A3,A4,A5,A6) \
  CCALLSFSUB6(MZDIV,mzdiv,INT,PINT,STRING,INT,INT,STRING,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB2(PAW,paw,INT,INT)
#define PAW(A1,A2) CCALLSFSUB2(PAW,paw,INT,INT,A1,A2)

  // Define common blocks
#include "gcbank.hh"
#include "gcflag.hh"
#include "pstore.hh"
#include "quest.hh"
#include "stosto.hh"
#include "iuhead.hh"
#include "pawc.hh"

