      integer NHIEVT
      real EFRM
      real BMIN0
      real BMAX0
      real THETAMIN
      real THETAMAX
      integer NACCEPTED
      integer IAP, IZP, IAT, IZT
      character*4 FRAME, HPROJ, HTARG
      integer TRIGGER_JET
      common/hijingpar/EFRM, FRAME, HPROJ, HTARG, IAP, IZP, IAT, IZT, 
     +                 NHIEVT, BMIN0, BMAX0, TRIGGER_JET,
     +                 THETAMIN, THETAMAX, NACCEPTED
