#ifndef __PHCENTRALTRACK_HH_
#define __PHCENTRALTRACK_HH_

#include "PHParticle.h"
#include "PHObject.h"
#include <iostream>

class PHSnglCentralTrack;
class TClonesArray;

class PHCentralTrack : public PHParticle
{


 public:
  virtual ~PHCentralTrack() {}
  // implementation of methods inherited from PHParticle
  virtual void set_npart(const unsigned int npart);
  virtual void set_px(const unsigned int itrk, const float val);
  virtual void set_py(const unsigned int itrk, const float val);
  virtual void set_pz(const unsigned int itrk, const float val);
  virtual void set_E(const unsigned int itrk, const float val);
  virtual void set_charge(const unsigned int itrk, const short val);
  virtual void set_PID(const unsigned int itrk, const short val);

  virtual unsigned int   get_npart() const;
  virtual float get_px(const unsigned int itrk) const;
  virtual float get_py(const unsigned int itrk) const;
  virtual float get_pz(const unsigned int itrk) const;
  virtual float get_E(const unsigned int itrk) const;
  virtual short get_charge(const unsigned int itrk) const;
  virtual short get_PID(const unsigned int itrk) const;

  // and here all the rest
  virtual void set_quality    (const unsigned int itrk, const short val);
  virtual void set_zed        (const unsigned int itrk, const float val);
  virtual void set_phi        (const unsigned int itrk, const float val);
  virtual void set_alpha      (const unsigned int itrk, const float val);
  virtual void set_beta       (const unsigned int itrk, const float val);
  virtual void set_phi0       (const unsigned int itrk, const float val);
  virtual void set_the0       (const unsigned int itrk, const float val);
  virtual void set_mom        (const unsigned int itrk, const float val);
  virtual void set_mompx      (const unsigned int itrk, const float val);
  virtual void set_mompy      (const unsigned int itrk, const float val);
  virtual void set_mompz      (const unsigned int itrk, const float val);
  virtual void set_status     (const unsigned int itrk, const short val);
  virtual void set_alpha1     (const unsigned int itrk, const float val);
  virtual void set_alpha2     (const unsigned int itrk, const float val);
  virtual void set_nx1hits    (const unsigned int itrk, const short val);
  virtual void set_nx2hits    (const unsigned int itrk, const short val);
  virtual void set_mx1dist    (const unsigned int itrk, const float val);
  virtual void set_mx2dist    (const unsigned int itrk, const float val);
  virtual void set_chi2x1     (const unsigned int itrk, const float val);
  virtual void set_chi2x2     (const unsigned int itrk, const float val);
  virtual void set_nx1x2fit   (const unsigned int itrk, const short val);
  virtual void set_mchi2      (const unsigned int itrk, const float val);
  virtual void set_error      (const unsigned int itrk, const float val);
  virtual void set_alphaf     (const unsigned int itrk, const float val);
  virtual void set_pc1id      (const unsigned int itrk, const short val);
  virtual void set_pc2id      (const unsigned int itrk, const short val);
  virtual void set_pc3id      (const unsigned int itrk, const short val);
  virtual void set_emcid      (const unsigned int itrk, const short val);
  virtual void set_tofid      (const unsigned int itrk, const short val);
  virtual void set_tecid      (const unsigned int itrk, const short val);
  virtual void set_hbdid      (const unsigned int itrk, const short val);
  virtual void set_mrpcid     (const unsigned int itrk, const short val);
  virtual void set_tofwid     (const unsigned int itrk, const short val);
  virtual void set_spc2id     (const unsigned int itrk, const short val);
  virtual void set_spc3id     (const unsigned int itrk, const short val);
  virtual void set_semcid     (const unsigned int itrk, const short val);
  virtual void set_stofid     (const unsigned int itrk, const short val);
  virtual void set_stecid     (const unsigned int itrk, const short val);
  virtual void set_ppc1x      (const unsigned int itrk, const float val);
  virtual void set_ppc1y      (const unsigned int itrk, const float val);
  virtual void set_ppc1z      (const unsigned int itrk, const float val);
  virtual void set_ppc2x      (const unsigned int itrk, const float val);
  virtual void set_ppc2y      (const unsigned int itrk, const float val);
  virtual void set_ppc2z      (const unsigned int itrk, const float val);
  virtual void set_ptecx      (const unsigned int itrk, const float val);
  virtual void set_ptecy      (const unsigned int itrk, const float val);
  virtual void set_ptecz      (const unsigned int itrk, const float val);
  virtual void set_ppc3x      (const unsigned int itrk, const float val);
  virtual void set_ppc3y      (const unsigned int itrk, const float val);
  virtual void set_ppc3z      (const unsigned int itrk, const float val);
  virtual void set_pemcx      (const unsigned int itrk, const float val);
  virtual void set_pemcy      (const unsigned int itrk, const float val);
  virtual void set_pemcz      (const unsigned int itrk, const float val);
  virtual void set_ptofx      (const unsigned int itrk, const float val);
  virtual void set_ptofy      (const unsigned int itrk, const float val);
  virtual void set_ptofz      (const unsigned int itrk, const float val);
  virtual void set_phbdx      (const unsigned int itrk, const float val);
  virtual void set_phbdy      (const unsigned int itrk, const float val);
  virtual void set_phbdz      (const unsigned int itrk, const float val);
  virtual void set_pmrpcx     (const unsigned int itrk, const float val);
  virtual void set_pmrpcy     (const unsigned int itrk, const float val);
  virtual void set_pmrpcz     (const unsigned int itrk, const float val);
  virtual void set_ptofwx     (const unsigned int itrk, const float val);
  virtual void set_ptofwy     (const unsigned int itrk, const float val);
  virtual void set_ptofwz     (const unsigned int itrk, const float val);
  virtual void set_pltof      (const unsigned int itrk, const float val);
  virtual void set_plemc      (const unsigned int itrk, const float val);
  virtual void set_plmrpc     (const unsigned int itrk, const float val);
  virtual void set_pltofw     (const unsigned int itrk, const float val);
  virtual void set_pc2dphi    (const unsigned int itrk, const float val);
  virtual void set_pc2dz      (const unsigned int itrk, const float val);
  virtual void set_pc3dphi    (const unsigned int itrk, const float val);
  virtual void set_pc3dz      (const unsigned int itrk, const float val);
  virtual void set_emcdphi    (const unsigned int itrk, const float val);
  virtual void set_emcdz      (const unsigned int itrk, const float val);
  virtual void set_tofdphi    (const unsigned int itrk, const float val);
  virtual void set_tofdz      (const unsigned int itrk, const float val);
  virtual void set_tofwdphi   (const unsigned int itrk, const float val);
  virtual void set_tofwdz     (const unsigned int itrk, const float val);
  virtual void set_tecdphi    (const unsigned int itrk, const float val);
  virtual void set_tecdalpha  (const unsigned int itrk, const float val);
  virtual void set_mrpcdphi   (const unsigned int itrk, const float val);
  virtual void set_mrpcdz     (const unsigned int itrk, const float val);
  virtual void set_spc2dphi   (const unsigned int itrk, const float val);
  virtual void set_spc2dz     (const unsigned int itrk, const float val);
  virtual void set_spc3dphi   (const unsigned int itrk, const float val);
  virtual void set_spc3dz     (const unsigned int itrk, const float val);
  virtual void set_semcdphi   (const unsigned int itrk, const float val);
  virtual void set_semcdz     (const unsigned int itrk, const float val);
  virtual void set_stofdphi   (const unsigned int itrk, const float val);
  virtual void set_stofdz     (const unsigned int itrk, const float val);
  virtual void set_stofwdphi  (const unsigned int itrk, const float val);
  virtual void set_stofwdz    (const unsigned int itrk, const float val);
  virtual void set_stecdphi   (const unsigned int itrk, const float val);
  virtual void set_stecdalpha (const unsigned int itrk, const float val);
  virtual void set_hbdsector  (const unsigned int itrk, const short val);
  virtual void set_hbdsize    (const unsigned int itrk, const short val);
  virtual void set_hbdcharge  (const unsigned int itrk, const float val);
  virtual void set_hbdx       (const unsigned int itrk, const float val);
  virtual void set_hbdy       (const unsigned int itrk, const float val);
  virtual void set_hbdz       (const unsigned int itrk, const float val);
  virtual void set_hbddphi    (const unsigned int itrk, const float val);
  virtual void set_hbddz      (const unsigned int itrk, const float val);
  virtual void set_hbdsdphi   (const unsigned int itrk, const float val);
  virtual void set_hbdsdz     (const unsigned int itrk, const float val);
  virtual void set_arm        (const unsigned int itrk, const short val);
  virtual void set_sect       (const unsigned int itrk, const short val);
  virtual void set_ysect      (const unsigned int itrk, const short val);
  virtual void set_zsect      (const unsigned int itrk, const short val);
  virtual void set_ecorr      (const unsigned int itrk, const float val);
  virtual void set_ecore      (const unsigned int itrk, const float val);
  virtual void set_dep        (const unsigned int itrk, const float val);
  virtual void set_emce	      (const unsigned int itrk, const float val);
  virtual void set_emcdispy   (const unsigned int itrk, const float val);
  virtual void set_emcdispz   (const unsigned int itrk, const float val);
  virtual void set_temc       (const unsigned int itrk, const float val);
  virtual void set_prob       (const unsigned int itrk, const float val);
  virtual void set_ecent      (const unsigned int itrk, const float val);
  virtual void set_twrhit     (const unsigned int itrk, const short val);
  virtual void set_e9         (const unsigned int itrk, const float val);
  virtual void set_re9        (const unsigned int itrk, const float val);
  virtual void set_emcchi2    (const unsigned int itrk, const float val);
  virtual void set_sysect     (const unsigned int itrk, const short val);
  virtual void set_szsect     (const unsigned int itrk, const short val);
  virtual void set_secorr     (const unsigned int itrk, const float val);
  virtual void set_secore     (const unsigned int itrk, const float val);
  virtual void set_semce      (const unsigned int itrk, const float val);
  virtual void set_semcdispy  (const unsigned int itrk, const float val);
  virtual void set_semcdispz  (const unsigned int itrk, const float val);
  virtual void set_stemc      (const unsigned int itrk, const float val);
  virtual void set_sprob      (const unsigned int itrk, const float val);
  virtual void set_secent     (const unsigned int itrk, const float val);
  virtual void set_stwrhit    (const unsigned int itrk, const short val);
  virtual void set_se9        (const unsigned int itrk, const float val);
  virtual void set_sre9       (const unsigned int itrk, const float val);
  virtual void set_semcchi2   (const unsigned int itrk, const float val);
  virtual void set_slat       (const unsigned int itrk, const int   val);
  virtual void set_ttof       (const unsigned int itrk, const float val);
  virtual void set_etof       (const unsigned int itrk, const float val);
  virtual void set_sttof      (const unsigned int itrk, const float val);
  virtual void set_setof      (const unsigned int itrk, const float val);
  virtual void set_slat_mrpc  (const unsigned int itrk, const int   val);
  virtual void set_ttof_mrpc  (const unsigned int itrk, const float val);
  virtual void set_ttofd_mrpc (const unsigned int itrk, const float val);
  virtual void set_qtof_mrpc  (const unsigned int itrk, const float val);
  virtual void set_striptofw  (const unsigned int itrk, const int   val);

  virtual void set_tofwx      (const unsigned int itrk, const float val);
  virtual void set_tofwy      (const unsigned int itrk, const float val);
  virtual void set_tofwz      (const unsigned int itrk, const float val);

  virtual void set_ttofw      (const unsigned int itrk, const float val);
  virtual void set_qtofw      (const unsigned int itrk, const float val);
  virtual void set_tofwadcup  (const unsigned int itrk, const float val);
  virtual void set_tofwadcdw  (const unsigned int itrk, const float val);
  virtual void set_tofwtdcup  (const unsigned int itrk, const float val);
  virtual void set_tofwtdcdw  (const unsigned int itrk, const float val);
  virtual void set_acc        (const unsigned int itrk, const short val);
  virtual void set_ring       (const unsigned int itrk, const int   val);
  virtual void set_n0         (const unsigned int itrk, const short val);
  virtual void set_npe0       (const unsigned int itrk, const float val);
  virtual void set_n1         (const unsigned int itrk, const short val);
  virtual void set_npe1       (const unsigned int itrk, const float val);
  virtual void set_chi2       (const unsigned int itrk, const float val);
  virtual void set_disp       (const unsigned int itrk, const float val);
  virtual void set_tcrk       (const unsigned int itrk, const float val);
  virtual void set_cross_phi  (const unsigned int itrk, const float val);
  virtual void set_cross_z    (const unsigned int itrk, const float val);
  virtual void set_center_phi (const unsigned int itrk, const float val);
  virtual void set_center_z   (const unsigned int itrk, const float val);
  virtual void set_sacc       (const unsigned int itrk, const short val);
  virtual void set_sring      (const unsigned int itrk, const int   val);
  virtual void set_sn0        (const unsigned int itrk, const short val);
  virtual void set_snpe0      (const unsigned int itrk, const float val);
  virtual void set_sn1        (const unsigned int itrk, const short val);
  virtual void set_snpe1      (const unsigned int itrk, const float val);
  virtual void set_schi2      (const unsigned int itrk, const float val);
  virtual void set_sdisp      (const unsigned int itrk, const float val);
  virtual void set_stcrk      (const unsigned int itrk, const float val);
  virtual void set_scross_phi (const unsigned int itrk, const float val);
  virtual void set_scross_z   (const unsigned int itrk, const float val);
  virtual void set_scenter_phi(const unsigned int itrk, const float val);
  virtual void set_scenter_z  (const unsigned int itrk, const float val);
  virtual void set_tecdedx1   (const unsigned int itrk, const float val);
  virtual void set_tecdedx2   (const unsigned int itrk, const float val);
  virtual void set_pc2sdphi   (const unsigned int itrk, const float val);
  virtual void set_pc2sdz     (const unsigned int itrk, const float val);
  virtual void set_pc3sdphi   (const unsigned int itrk, const float val);
  virtual void set_pc3sdz     (const unsigned int itrk, const float val);
  virtual void set_emcsdphi   (const unsigned int itrk, const float val);
  virtual void set_emcsdz     (const unsigned int itrk, const float val);
  virtual void set_tofsdphi   (const unsigned int itrk, const float val);
  virtual void set_tofsdz     (const unsigned int itrk, const float val);
  virtual void set_tofwsdphi  (const unsigned int itrk, const float val);
  virtual void set_tofwsdz    (const unsigned int itrk, const float val);
  virtual void set_tecsdphi   (const unsigned int itrk, const float val);
  virtual void set_tecsdalpha (const unsigned int itrk, const float val);
  virtual void set_spc2sdphi  (const unsigned int itrk, const float val);
  virtual void set_spc2sdz    (const unsigned int itrk, const float val);
  virtual void set_spc3sdphi  (const unsigned int itrk, const float val);
  virtual void set_spc3sdz    (const unsigned int itrk, const float val);
  virtual void set_semcsdphi  (const unsigned int itrk, const float val);
  virtual void set_semcsdz    (const unsigned int itrk, const float val);
  virtual void set_stofsdphi  (const unsigned int itrk, const float val);
  virtual void set_stofsdz    (const unsigned int itrk, const float val);
  virtual void set_stofwsdphi (const unsigned int itrk, const float val);
  virtual void set_stofwsdz   (const unsigned int itrk, const float val);
  virtual void set_stecsdphi  (const unsigned int itrk, const float val);
  virtual void set_stecsdalpha(const unsigned int itrk, const float val);
  virtual void set_m2tof      (const unsigned int itrk, const float val);
  virtual void set_m2tofw     (const unsigned int itrk, const float val);
  virtual void set_m2emc      (const unsigned int itrk, const float val);
  virtual void set_isPi       (const unsigned int itrk, const float val);
  virtual void set_isK        (const unsigned int itrk, const float val);
  virtual void set_isP        (const unsigned int itrk, const float val);
  virtual void set_isPiTofw   (const unsigned int itrk, const float val);
  virtual void set_isKTofw    (const unsigned int itrk, const float val);
  virtual void set_isPTofw    (const unsigned int itrk, const float val);
  virtual void set_dcarm      (const unsigned int itrk, const short val);
  virtual void set_dcside     (const unsigned int itrk, const short val);
  virtual void set_pc1sect    (const unsigned int itrk, const short val);
  virtual void set_pc2sect    (const unsigned int itrk, const short val);
  virtual void set_pc3sect    (const unsigned int itrk, const short val);
  virtual void set_pc1phi     (const unsigned int itrk, const float val);
  virtual void set_pc1z	      (const unsigned int itrk, const float val);
  virtual void set_pc2phi     (const unsigned int itrk, const float val);
  virtual void set_pc2z	      (const unsigned int itrk, const float val);
  virtual void set_pc3phi     (const unsigned int itrk, const float val);
  virtual void set_pc3z	      (const unsigned int itrk, const float val);
  virtual void set_tofphi     (const unsigned int itrk, const float val);
  virtual void set_tofz	      (const unsigned int itrk, const float val);
  virtual void set_tecphi     (const unsigned int itrk, const float val);
  virtual void set_tecalpha   (const unsigned int itrk, const float val);
  virtual void set_emcphi     (const unsigned int itrk, const float val);
  virtual void set_emcz	      (const unsigned int itrk, const float val);
  virtual void set_spc1phi    (const unsigned int itrk, const float val);
  virtual void set_spc1z      (const unsigned int itrk, const float val);
  virtual void set_spc2phi    (const unsigned int itrk, const float val);
  virtual void set_spc2z      (const unsigned int itrk, const float val);
  virtual void set_spc3phi    (const unsigned int itrk, const float val);
  virtual void set_spc3z      (const unsigned int itrk, const float val);
  virtual void set_stofphi    (const unsigned int itrk, const float val);
  virtual void set_stofz      (const unsigned int itrk, const float val);
  virtual void set_stecphi    (const unsigned int itrk, const float val);
  virtual void set_stecalpha  (const unsigned int itrk, const float val);
  virtual void set_semcphi    (const unsigned int itrk, const float val);
  virtual void set_semcz      (const unsigned int itrk, const float val);
  virtual void set_emcsdphi_e (const unsigned int itrk, const float val);
  virtual void set_emcsdz_e   (const unsigned int itrk, const float val);
  virtual void set_semcsdphi_e(const unsigned int itrk, const float val);
  virtual void set_semcsdz_e  (const unsigned int itrk, const float val);
  virtual void set_tecnhit    (const unsigned int itrk, const short val);
  virtual void set_n2	      (const unsigned int itrk, const short val);
  virtual void set_npe2	      (const unsigned int itrk, const float val);
  virtual void set_n3	      (const unsigned int itrk, const short val);
  virtual void set_npe3	      (const unsigned int itrk, const float val);
  virtual void set_sn2	      (const unsigned int itrk, const short val);
  virtual void set_snpe2      (const unsigned int itrk, const float val);
  virtual void set_sn3	      (const unsigned int itrk, const short val);
  virtual void set_snpe3      (const unsigned int itrk, const float val);
  virtual void set_deadmap    (const unsigned int itrk, const int   val);
  virtual void set_warnmap    (const unsigned int itrk, const int   val);
  virtual void set_sdeadmap   (const unsigned int itrk, const int   val);
  virtual void set_swarnmap   (const unsigned int itrk, const int   val);
  virtual void set_tofecut    (const unsigned int itrk, const short val);
  virtual void set_tofsame    (const unsigned int itrk, const short val);
  virtual void set_slatnext   (const unsigned int itrk, const short val);
  virtual void set_ttofnext   (const unsigned int itrk, const float val);
  virtual void set_etofnext   (const unsigned int itrk, const float val);
  virtual void set_tzrid      (const unsigned int itrk, const short val);
  virtual void set_pcrid      (const unsigned int itrk, const short val);
  virtual void set_ptzrx      (const unsigned int itrk, const float val);
  virtual void set_ptzry      (const unsigned int itrk, const float val);
  virtual void set_ptzrz      (const unsigned int itrk, const float val);
  virtual void set_ppcrx      (const unsigned int itrk, const float val);
  virtual void set_ppcry      (const unsigned int itrk, const float val);
  virtual void set_ppcrz      (const unsigned int itrk, const float val);
  virtual void set_tzrtof     (const unsigned int itrk, const float val);
  virtual void set_tzrslat    (const unsigned int itrk, const short val);
  virtual void set_tzreloss   (const unsigned int itrk, const float val);
  virtual void set_tzrx	      (const unsigned int itrk, const float val);
  virtual void set_tzry	      (const unsigned int itrk, const float val);
  virtual void set_tzrz	      (const unsigned int itrk, const float val);
  virtual void set_pcrtof   (const unsigned int itrk, const float val);  
  virtual void set_pcrslat  (const unsigned int itrk, const short val);  
  virtual void set_pcreloss (const unsigned int itrk, const float val);
  virtual void set_pcrx	    (const unsigned int itrk, const float val);
  virtual void set_pcry	    (const unsigned int itrk, const float val);
  virtual void set_pcrz	    (const unsigned int itrk, const float val);
  // new stuff HWG v3
  virtual void set_tzrsdphi (const unsigned int itrk, const float val);
  virtual void set_tzrsdz   (const unsigned int itrk, const float val);
  virtual void set_m2tzr    (const unsigned int itrk, const float val);
  virtual void set_m2ntctof (const unsigned int itrk, const float val);
  virtual void set_pltzr    (const unsigned int itrk, const float val);
  virtual void set_isPitzr  (const unsigned int itrk, const float val);
  virtual void set_isKtzr   (const unsigned int itrk, const float val);
  virtual void set_isPtzr   (const unsigned int itrk, const float val);
  virtual void set_isPintctof(const unsigned int itrk, const float val);
  virtual void set_isKntctof(const unsigned int itrk, const float val);
  virtual void set_isPntctof(const unsigned int itrk, const float val);
  virtual void set_tzrecut  (const unsigned int itrk, const short val);
  virtual void set_L1Trig   (const unsigned int itrk, const int   val);
  virtual void set_pc1wid   (const unsigned int itrk, const float val);
  virtual void set_pc2wid   (const unsigned int itrk, const float val);
  virtual void set_pc3wid   (const unsigned int itrk, const float val);
  virtual void set_categoryl2eLowPt(const unsigned int itrk, const long val);
  virtual void set_categoryl2eHighPt(const unsigned int itrk, const long val);
  virtual void set_candIDl2e(const unsigned int itrk, const short val);
  virtual void set_nlvl2MatchLowOcupy(const unsigned int itrk, const int val);
  virtual void set_RawL1        (const unsigned int itrk, const int val);
  virtual void set_LivL1        (const unsigned int itrk, const int val);
  virtual void set_SclL1        (const unsigned int itrk, const int val);
  virtual void set_tofph1       (const unsigned int itrk, const float val);
  virtual void set_tofph2       (const unsigned int itrk, const float val);
  virtual void set_toftdc1      (const unsigned int itrk, const float val);
  virtual void set_toftdc2      (const unsigned int itrk, const float val);
  virtual void set_aerindex     (const unsigned int itrk, const int val);
  virtual void set_aersindex    (const unsigned int itrk, const int val);
  virtual void set_aerph1       (const unsigned int itrk, const float val);
  virtual void set_aerph2       (const unsigned int itrk, const float val);
  virtual void set_aert1        (const unsigned int itrk, const float val);
  virtual void set_aert2        (const unsigned int itrk, const float val);
  virtual void set_aernpe       (const unsigned int itrk, const float val);
  virtual void set_aerstatus    (const unsigned int itrk, const short val);
  virtual void set_aerph1_0       (const unsigned int itrk, const float val);
  virtual void set_aerph2_0       (const unsigned int itrk, const float val);
  virtual void set_aert1_0        (const unsigned int itrk, const float val);
  virtual void set_aert2_0        (const unsigned int itrk, const float val);
  virtual void set_aerph1_1       (const unsigned int itrk, const float val);
  virtual void set_aerph2_1       (const unsigned int itrk, const float val);
  virtual void set_aert1_1        (const unsigned int itrk, const float val);
  virtual void set_aert2_1        (const unsigned int itrk, const float val);
  virtual void set_aerph1_2       (const unsigned int itrk, const float val);
  virtual void set_aerph2_2       (const unsigned int itrk, const float val);
  virtual void set_aert1_2        (const unsigned int itrk, const float val);
  virtual void set_aert2_2        (const unsigned int itrk, const float val);
  virtual void set_aerph1_3       (const unsigned int itrk, const float val);
  virtual void set_aerph2_3       (const unsigned int itrk, const float val);
  virtual void set_aert1_3        (const unsigned int itrk, const float val);
  virtual void set_aert2_3        (const unsigned int itrk, const float val);
  virtual void set_aerhitid       (const unsigned int itrk, const int val);
  virtual void set_aerhitconfig   (const unsigned int itrk, const int val);
  virtual void set_aersph1_0       (const unsigned int itrk, const float val);
  virtual void set_aersph2_0       (const unsigned int itrk, const float val);
  virtual void set_aerst1_0        (const unsigned int itrk, const float val);
  virtual void set_aerst2_0        (const unsigned int itrk, const float val);
  virtual void set_aersph1_1       (const unsigned int itrk, const float val);
  virtual void set_aersph2_1       (const unsigned int itrk, const float val);
  virtual void set_aerst1_1        (const unsigned int itrk, const float val);
  virtual void set_aerst2_1        (const unsigned int itrk, const float val);
  virtual void set_aersph1_2       (const unsigned int itrk, const float val);
  virtual void set_aersph2_2       (const unsigned int itrk, const float val);
  virtual void set_aerst1_2        (const unsigned int itrk, const float val);
  virtual void set_aerst2_2        (const unsigned int itrk, const float val);
  virtual void set_aersph1_3       (const unsigned int itrk, const float val);
  virtual void set_aersph2_3       (const unsigned int itrk, const float val);
  virtual void set_aerst1_3        (const unsigned int itrk, const float val);
  virtual void set_aerst2_3        (const unsigned int itrk, const float val);
  virtual void set_aershitid       (const unsigned int itrk, const int val);
  virtual void set_aershitconfig   (const unsigned int itrk, const int val);
  virtual void set_tecde      (const unsigned int itrk, const float val);
  virtual void set_tecde06    (const unsigned int itrk, const float val);
  virtual void set_tectrklen  (const unsigned int itrk, const float val);
  virtual void set_tecnde     (const unsigned int itrk, const short val);
  virtual void set_tecnhit100 (const unsigned int itrk, const short val);
  virtual void set_tecnhit200 (const unsigned int itrk, const short val);
  virtual void set_tecnhit50  (const unsigned int itrk, const short val);
  virtual void set_tecwtb     (const unsigned int itrk, const float val);
  virtual void set_tecwtbsq   (const unsigned int itrk, const float val);
  virtual void set_mcid       (const unsigned int itrk, const int   val);
  virtual void set_dchid      (const unsigned int itrk, const int   val);
  virtual void set_emcrawtdc  (const unsigned int itrk, const int   val);
  virtual void set_emcrawadc  (const unsigned int itrk, const int   val);
  virtual void set_emcrawadclg(const unsigned int itrk, const int   val);
  virtual void set_Px(const unsigned int itrk, const float val);
  virtual void set_Py(const unsigned int itrk, const float val);
  virtual void set_Pz(const unsigned int itrk, const float val);
  virtual void set_idtrk_tof(const unsigned int itrk, const int val);
  virtual void set_idtrk_tofw(const unsigned int itrk, const int val);
  virtual void set_idtrk_tec(const unsigned int itrk, const int val);
  virtual void set_idtrk_crk(const unsigned int itrk, const int val);
  virtual void set_idtrk_pc2(const unsigned int itrk, const int val);
  virtual void set_idtrk_pc3(const unsigned int itrk, const int val);
  virtual void set_idtrk_hbd(const unsigned int itrk, const int val);
  virtual void set_idtrk_stof(const unsigned int itrk, const int val);
  virtual void set_idtrk_stec(const unsigned int itrk, const int val);
  virtual void set_idtrk_scrk(const unsigned int itrk, const int val);
  virtual void set_idtrk_spc2(const unsigned int itrk, const int val);
  virtual void set_idtrk_spc3(const unsigned int itrk, const int val);
  virtual void set_hbdhubcharge(const unsigned int itrk, const float val);
  virtual void set_hbdspokecharge1  (const unsigned int itrk, const float val);
  virtual void set_hbdspokecharge2  (const unsigned int itrk, const float val);
  virtual void set_hbdscharge (const unsigned int itrk, const float val);
  virtual void set_hbdlocalmax(const unsigned int itrk, const float val);

  virtual void set_teccharge          (const unsigned int itrk, const unsigned int iplane, const float val);
  virtual void set_tecdphiplane       (const unsigned int itrk, const unsigned int iplane, const float val);
  virtual void set_tecntimebins       (const unsigned int itrk, const unsigned int iplane, const int val);
  virtual void set_tecavgtimebin      (const unsigned int itrk, const unsigned int iplane, const int val);
  virtual void set_steccharge         (const unsigned int itrk, const unsigned int iplane, const float val);
  virtual void set_stecdphiplane      (const unsigned int itrk, const unsigned int iplane, const float val);
  virtual void set_stecntimebins      (const unsigned int itrk, const unsigned int iplane, const int val);
  virtual void set_stecavgtimebin     (const unsigned int itrk, const unsigned int iplane, const int val);

  // Silicon Vertex (SVX) stuff
  virtual void set_svxdphi            (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_svxdz              (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_svxid              (const unsigned int itrk, const unsigned int ilayer, const int val);           
  virtual void set_svxsdphi           (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_svxsdz             (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_svxsid             (const unsigned int itrk, const unsigned int ilayer, const int val);           
  virtual void set_psvxx              (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_psvxy              (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_psvxz              (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_spsvxx             (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_spsvxy             (const unsigned int itrk, const unsigned int ilayer, const float val);           
  virtual void set_spsvxz             (const unsigned int itrk, const unsigned int ilayer, const float val);           
  // entries above are for svx clusters, entries below ate for svx standalone tracks
  virtual void set_svxtrackid         (const unsigned int itrk, const int val);           
  virtual void set_svxtrackquality           (const unsigned int itrk, const float val); // standalone          
  virtual void set_svxdca2d           (const unsigned int itrk, const float val); // standalone          
  virtual void set_svxdca3d           (const unsigned int itrk, const float val);           
  virtual void set_svxdca2dkf         (const unsigned int itrk, const float val); // KalFit           
  virtual void set_svxdca3dkf         (const unsigned int itrk, const float val);           
  // The entries below represent a point of closest approach, and
  // track momentum components ar this point.
  // They are needed for secondary vertex determination for a pair of tracks
  // They come in two flavors: one determined by svx standalone tracking (0)
  // and the second one determined by KalFit (kf)
  virtual void set_svxxyz0              (const unsigned int itrk, const unsigned int icoor, const float val);           
  virtual void set_svxpxyz0             (const unsigned int itrk, const unsigned int icoor, const float val);           
  virtual void set_svxxyzkf             (const unsigned int itrk, const unsigned int icoor, const float val);           
  virtual void set_svxpxyzkf            (const unsigned int itrk, const unsigned int icoor, const float val);           


  // Get the values from the centralTrack...
  // The virtual base class prints warning then returns crap...
  virtual short get_quality    (const unsigned int itrk) const;
  virtual float get_zed        (const unsigned int itrk) const;
  virtual float get_phi        (const unsigned int itrk) const;
  virtual float get_alpha      (const unsigned int itrk) const;
  virtual float get_beta       (const unsigned int itrk) const;
  virtual float get_phi0       (const unsigned int itrk) const;
  virtual float get_the0       (const unsigned int itrk) const;
  virtual float get_mom        (const unsigned int itrk) const;
  virtual float get_mompx      (const unsigned int itrk) const;
  virtual float get_mompy      (const unsigned int itrk) const;
  virtual float get_mompz      (const unsigned int itrk) const;
  virtual short get_status     (const unsigned int itrk) const;
  virtual float get_alpha1     (const unsigned int itrk) const;
  virtual float get_alpha2     (const unsigned int itrk) const;
  virtual short get_nx1hits    (const unsigned int itrk) const;
  virtual short get_nx2hits    (const unsigned int itrk) const;
  virtual float get_mx1dist    (const unsigned int itrk) const;
  virtual float get_mx2dist    (const unsigned int itrk) const;
  virtual float get_chi2x1     (const unsigned int itrk) const;
  virtual float get_chi2x2     (const unsigned int itrk) const;
  virtual short get_nx1x2fit   (const unsigned int itrk) const;
  virtual float get_mchi2      (const unsigned int itrk) const;
  virtual float get_error      (const unsigned int itrk) const;
  virtual float get_alphaf     (const unsigned int itrk) const;
  virtual short get_pc1id      (const unsigned int itrk) const;
  virtual short get_pc2id      (const unsigned int itrk) const;
  virtual short get_pc3id      (const unsigned int itrk) const;
  virtual short get_emcid      (const unsigned int itrk) const;
  virtual short get_tofid      (const unsigned int itrk) const;
  virtual short get_tecid      (const unsigned int itrk) const;
  virtual short get_mrpcid     (const unsigned int itrk) const;
  virtual short get_tofwid     (const unsigned int itrk) const;
  virtual short get_hbdid      (const unsigned int itrk) const;
  virtual short get_spc2id     (const unsigned int itrk) const;
  virtual short get_spc3id     (const unsigned int itrk) const;
  virtual short get_semcid     (const unsigned int itrk) const;
  virtual short get_stofid     (const unsigned int itrk) const;
  virtual short get_stecid     (const unsigned int itrk) const;
  virtual float get_ppc1x      (const unsigned int itrk) const;
  virtual float get_ppc1y      (const unsigned int itrk) const;
  virtual float get_ppc1z      (const unsigned int itrk) const;
  virtual float get_ppc2x      (const unsigned int itrk) const;
  virtual float get_ppc2y      (const unsigned int itrk) const;
  virtual float get_ppc2z      (const unsigned int itrk) const;
  virtual float get_ptecx      (const unsigned int itrk) const;
  virtual float get_ptecy      (const unsigned int itrk) const;
  virtual float get_ptecz      (const unsigned int itrk) const;
  virtual float get_ppc3x      (const unsigned int itrk) const;
  virtual float get_ppc3y      (const unsigned int itrk) const;
  virtual float get_ppc3z      (const unsigned int itrk) const;
  virtual float get_pemcx      (const unsigned int itrk) const;
  virtual float get_pemcy      (const unsigned int itrk) const;
  virtual float get_pemcz      (const unsigned int itrk) const;
  virtual float get_ptofx      (const unsigned int itrk) const;
  virtual float get_ptofy      (const unsigned int itrk) const;
  virtual float get_ptofz      (const unsigned int itrk) const;
  virtual float get_phbdx      (const unsigned int itrk) const;
  virtual float get_phbdy      (const unsigned int itrk) const;
  virtual float get_phbdz      (const unsigned int itrk) const;
  virtual float get_pmrpcx     (const unsigned int itrk) const;
  virtual float get_pmrpcy     (const unsigned int itrk) const;
  virtual float get_pmrpcz     (const unsigned int itrk) const;
  virtual float get_ptofwx     (const unsigned int itrk) const;
  virtual float get_ptofwy     (const unsigned int itrk) const;
  virtual float get_ptofwz     (const unsigned int itrk) const;
  virtual float get_pltof      (const unsigned int itrk) const;
  virtual float get_plemc      (const unsigned int itrk) const;
  virtual float get_plmrpc     (const unsigned int itrk) const;
  virtual float get_pltofw     (const unsigned int itrk) const;
  virtual float get_pc2dphi    (const unsigned int itrk) const;
  virtual float get_pc2dz      (const unsigned int itrk) const;
  virtual float get_tecdphi    (const unsigned int itrk) const;
  virtual float get_tecdalpha  (const unsigned int itrk) const;
  virtual float get_pc3dphi    (const unsigned int itrk) const;
  virtual float get_pc3dz      (const unsigned int itrk) const;
  virtual float get_emcdphi    (const unsigned int itrk) const;
  virtual float get_emcdz      (const unsigned int itrk) const;
  virtual float get_tofdphi    (const unsigned int itrk) const;
  virtual float get_tofdz      (const unsigned int itrk) const;
  virtual float get_mrpcdphi   (const unsigned int itrk) const;
  virtual float get_mrpcdz     (const unsigned int itrk) const;
  virtual float get_tofwdphi   (const unsigned int itrk) const;
  virtual float get_tofwdz     (const unsigned int itrk) const;
  virtual float get_spc2dphi   (const unsigned int itrk) const;
  virtual float get_spc2dz     (const unsigned int itrk) const;
  virtual float get_spc3dphi   (const unsigned int itrk) const;
  virtual float get_spc3dz     (const unsigned int itrk) const;
  virtual float get_semcdphi   (const unsigned int itrk) const;
  virtual float get_semcdz     (const unsigned int itrk) const;
  virtual float get_stofdphi   (const unsigned int itrk) const;
  virtual float get_stofdz     (const unsigned int itrk) const;
  virtual float get_stofwdphi  (const unsigned int itrk) const;
  virtual float get_stofwdz    (const unsigned int itrk) const;
  virtual float get_stecdphi   (const unsigned int itrk) const;
  virtual float get_stecdalpha (const unsigned int itrk) const;
  virtual short get_hbdsector  (const unsigned int itrk) const;
  virtual short get_hbdsize    (const unsigned int itrk) const;
  virtual float get_hbdcharge  (const unsigned int itrk) const;
  virtual float get_hbdx       (const unsigned int itrk) const;
  virtual float get_hbdy       (const unsigned int itrk) const;
  virtual float get_hbdz       (const unsigned int itrk) const;
  virtual float get_hbddphi    (const unsigned int itrk) const;
  virtual float get_hbddz      (const unsigned int itrk) const;
  virtual float get_hbdsdphi   (const unsigned int itrk) const;
  virtual float get_hbdsdz     (const unsigned int itrk) const;
  virtual short get_arm        (const unsigned int itrk) const;
  virtual short get_sect       (const unsigned int itrk) const;
  virtual short get_ysect      (const unsigned int itrk) const;
  virtual short get_zsect      (const unsigned int itrk) const;
  virtual float get_ecorr      (const unsigned int itrk) const;
  virtual float get_ecore      (const unsigned int itrk) const;
  virtual float get_dep        (const unsigned int itrk) const;
  virtual float get_emce       (const unsigned int itrk) const;
  virtual float get_emcdispy   (const unsigned int itrk) const;
  virtual float get_emcdispz   (const unsigned int itrk) const;
  virtual float get_temc       (const unsigned int itrk) const;
  virtual float get_prob       (const unsigned int itrk) const;
  virtual float get_ecent      (const unsigned int itrk) const;
  virtual short get_twrhit     (const unsigned int itrk) const;
  virtual float get_e9         (const unsigned int itrk) const;
  virtual float get_re9        (const unsigned int itrk) const;
  virtual float get_emcchi2    (const unsigned int itrk) const;
  virtual short get_sysect     (const unsigned int itrk) const;
  virtual short get_szsect     (const unsigned int itrk) const;
  virtual float get_secorr     (const unsigned int itrk) const;
  virtual float get_secore     (const unsigned int itrk) const;
  virtual float get_semce      (const unsigned int itrk) const;
  virtual float get_semcdispy  (const unsigned int itrk) const;
  virtual float get_semcdispz  (const unsigned int itrk) const;
  virtual float get_stemc      (const unsigned int itrk) const;
  virtual float get_sprob      (const unsigned int itrk) const;
  virtual float get_secent     (const unsigned int itrk) const;
  virtual short get_stwrhit    (const unsigned int itrk) const;
  virtual float get_se9        (const unsigned int itrk) const;
  virtual float get_sre9       (const unsigned int itrk) const;
  virtual float get_semcchi2   (const unsigned int itrk) const;
  virtual int   get_slat       (const unsigned int itrk) const;
  virtual float get_ttof       (const unsigned int itrk) const;
  virtual float get_etof       (const unsigned int itrk) const;
  virtual float get_sttof      (const unsigned int itrk) const;
  virtual float get_setof      (const unsigned int itrk) const;
  virtual int   get_slat_mrpc  (const unsigned int itrk) const;
  virtual float get_ttof_mrpc  (const unsigned int itrk) const;
  virtual float get_ttofd_mrpc (const unsigned int itrk) const;
  virtual float get_qtof_mrpc  (const unsigned int itrk) const;
  virtual int   get_striptofw  (const unsigned int itrk) const;

  virtual float get_tofwx      (const unsigned int itrk) const;
  virtual float get_tofwy      (const unsigned int itrk) const;
  virtual float get_tofwz      (const unsigned int itrk) const;

  virtual float get_ttofw      (const unsigned int itrk) const;
  virtual float get_qtofw      (const unsigned int itrk) const;
  virtual float get_tofwadcup  (const unsigned int itrk) const;
  virtual float get_tofwadcdw  (const unsigned int itrk) const;
  virtual float get_tofwtdcup  (const unsigned int itrk) const;
  virtual float get_tofwtdcdw  (const unsigned int itrk) const;
  virtual short get_acc        (const unsigned int itrk) const;
  virtual int   get_ring       (const unsigned int itrk) const;
  virtual short get_n0         (const unsigned int itrk) const;
  virtual float get_npe0       (const unsigned int itrk) const;
  virtual short get_n1         (const unsigned int itrk) const;
  virtual float get_npe1       (const unsigned int itrk) const;
  virtual float get_chi2       (const unsigned int itrk) const;
  virtual float get_disp       (const unsigned int itrk) const;
  virtual float get_tcrk       (const unsigned int itrk) const;
  virtual float get_cross_phi  (const unsigned int itrk) const;
  virtual float get_cross_z    (const unsigned int itrk) const;
  virtual float get_center_phi (const unsigned int itrk) const;
  virtual float get_center_z   (const unsigned int itrk) const;
  virtual short get_sacc       (const unsigned int itrk) const;
  virtual int   get_sring      (const unsigned int itrk) const;
  virtual short get_sn0        (const unsigned int itrk) const;
  virtual float get_snpe0      (const unsigned int itrk) const;
  virtual short get_sn1        (const unsigned int itrk) const;
  virtual float get_snpe1      (const unsigned int itrk) const;
  virtual float get_schi2      (const unsigned int itrk) const;
  virtual float get_sdisp      (const unsigned int itrk) const;
  virtual float get_stcrk      (const unsigned int itrk) const;
  virtual float get_scross_phi (const unsigned int itrk) const;
  virtual float get_scross_z   (const unsigned int itrk) const;
  virtual float get_scenter_phi(const unsigned int itrk) const;
  virtual float get_scenter_z  (const unsigned int itrk) const;
  virtual float get_tecdedx1   (const unsigned int itrk) const;
  virtual float get_tecdedx2   (const unsigned int itrk) const;
  virtual float get_pc2sdphi   (const unsigned int itrk) const;
  virtual float get_pc2sdz     (const unsigned int itrk) const;
  virtual float get_pc3sdphi   (const unsigned int itrk) const;
  virtual float get_pc3sdz     (const unsigned int itrk) const;
  virtual float get_emcsdphi   (const unsigned int itrk) const;
  virtual float get_emcsdz     (const unsigned int itrk) const;
  virtual float get_tofsdphi   (const unsigned int itrk) const;
  virtual float get_tofwsdz    (const unsigned int itrk) const;
  virtual float get_tofwsdphi  (const unsigned int itrk) const;
  virtual float get_tofsdz     (const unsigned int itrk) const;
  virtual float get_tecsdphi   (const unsigned int itrk) const;
  virtual float get_tecsdalpha (const unsigned int itrk) const;
  virtual float get_spc2sdphi  (const unsigned int itrk) const;
  virtual float get_spc2sdz    (const unsigned int itrk) const;
  virtual float get_spc3sdphi  (const unsigned int itrk) const;
  virtual float get_spc3sdz    (const unsigned int itrk) const;
  virtual float get_semcsdphi  (const unsigned int itrk) const;
  virtual float get_semcsdz    (const unsigned int itrk) const;
  virtual float get_stofsdphi  (const unsigned int itrk) const;
  virtual float get_stofsdz    (const unsigned int itrk) const;
  virtual float get_stofwsdphi (const unsigned int itrk) const;
  virtual float get_stofwsdz   (const unsigned int itrk) const;
  virtual float get_stecsdphi  (const unsigned int itrk) const;
  virtual float get_stecsdalpha(const unsigned int itrk) const;
  virtual float get_m2tof      (const unsigned int itrk) const;
  virtual float get_m2tofw     (const unsigned int itrk) const;
  virtual float get_m2emc      (const unsigned int itrk) const;
  virtual float get_isPi       (const unsigned int itrk) const;
  virtual float get_isK        (const unsigned int itrk) const;
  virtual float get_isP        (const unsigned int itrk) const;
  virtual float get_isPiTofw   (const unsigned int itrk) const;
  virtual float get_isKTofw    (const unsigned int itrk) const;
  virtual float get_isPTofw    (const unsigned int itrk) const;
  virtual short get_dcarm      (const unsigned int itrk) const;
  virtual short get_dcside     (const unsigned int itrk) const;
  virtual short get_pc1sect    (const unsigned int itrk) const;
  virtual short get_pc2sect    (const unsigned int itrk) const;
  virtual short get_pc3sect    (const unsigned int itrk) const;
  virtual float get_pc1phi     (const unsigned int itrk) const;
  virtual float get_pc1z       (const unsigned int itrk) const;
  virtual float get_pc2phi     (const unsigned int itrk) const;
  virtual float get_pc2z       (const unsigned int itrk) const;
  virtual float get_pc3phi     (const unsigned int itrk) const;
  virtual float get_pc3z       (const unsigned int itrk) const;
  virtual float get_tofphi     (const unsigned int itrk) const;
  virtual float get_tofz       (const unsigned int itrk) const;
  virtual float get_tecphi     (const unsigned int itrk) const;
  virtual float get_tecalpha   (const unsigned int itrk) const;
  virtual float get_emcphi     (const unsigned int itrk) const;
  virtual float get_emcz       (const unsigned int itrk) const;
  virtual float get_spc1phi    (const unsigned int itrk) const;
  virtual float get_spc1z      (const unsigned int itrk) const;
  virtual float get_spc2phi    (const unsigned int itrk) const;
  virtual float get_spc2z      (const unsigned int itrk) const;
  virtual float get_spc3phi    (const unsigned int itrk) const;
  virtual float get_spc3z      (const unsigned int itrk) const;
  virtual float get_stofphi    (const unsigned int itrk) const;
  virtual float get_stofz      (const unsigned int itrk) const;
  virtual float get_stecphi    (const unsigned int itrk) const;
  virtual float get_stecalpha  (const unsigned int itrk) const;
  virtual float get_semcphi    (const unsigned int itrk) const;
  virtual float get_semcz      (const unsigned int itrk) const;
  virtual float get_emcsdphi_e (const unsigned int itrk) const;
  virtual float get_emcsdz_e   (const unsigned int itrk) const;
  virtual float get_semcsdphi_e(const unsigned int itrk) const;
  virtual float get_semcsdz_e  (const unsigned int itrk) const;
  virtual short get_tecnhit    (const unsigned int itrk) const;
  virtual short get_n2	       (const unsigned int itrk) const;
  virtual float get_npe2       (const unsigned int itrk) const;
  virtual short get_n3	       (const unsigned int itrk) const;
  virtual float get_npe3       (const unsigned int itrk) const;
  virtual short get_sn2	       (const unsigned int itrk) const;
  virtual float get_snpe2      (const unsigned int itrk) const;
  virtual short get_sn3	       (const unsigned int itrk) const;
  virtual float get_snpe3      (const unsigned int itrk) const;
  virtual int   get_deadmap    (const unsigned int itrk) const;
  virtual int   get_warnmap    (const unsigned int itrk) const;
  virtual int   get_sdeadmap   (const unsigned int itrk) const;
  virtual int   get_swarnmap   (const unsigned int itrk) const;
  virtual short get_tofecut    (const unsigned int itrk) const;
  virtual short get_tofsame    (const unsigned int itrk) const;
  virtual short get_slatnext   (const unsigned int itrk) const;
  virtual float get_ttofnext   (const unsigned int itrk) const;
  virtual float get_etofnext   (const unsigned int itrk) const;
  virtual short get_tzrid      (const unsigned int itrk) const;
  virtual short get_pcrid      (const unsigned int itrk) const;
  virtual float get_ptzrx      (const unsigned int itrk) const;
  virtual float get_ptzry      (const unsigned int itrk) const;
  virtual float get_ptzrz      (const unsigned int itrk) const;
  virtual float get_ppcrx      (const unsigned int itrk) const;
  virtual float get_ppcry      (const unsigned int itrk) const;
  virtual float get_ppcrz      (const unsigned int itrk) const;
  virtual float get_tzrtof     (const unsigned int itrk) const;
  virtual short get_tzrslat    (const unsigned int itrk) const;
  virtual float get_tzreloss   (const unsigned int itrk) const;
  virtual float get_tzrx       (const unsigned int itrk) const;
  virtual float get_tzry       (const unsigned int itrk) const;
  virtual float get_tzrz       (const unsigned int itrk) const;
  virtual float get_pcrtof     (const unsigned int itrk) const;
  virtual short get_pcrslat    (const unsigned int itrk) const;
  virtual float get_pcreloss   (const unsigned int itrk) const;
  virtual float get_pcrx       (const unsigned int itrk) const;
  virtual float get_pcry       (const unsigned int itrk) const;
  virtual float get_pcrz       (const unsigned int itrk) const;
  virtual float get_tzrsdphi   (const unsigned int itrk) const;
  virtual float get_tzrsdz     (const unsigned int itrk) const;
  virtual float get_m2tzr      (const unsigned int itrk) const;
  virtual float get_m2ntctof   (const unsigned int itrk) const;
  virtual float get_pltzr      (const unsigned int itrk) const;
  virtual float get_isPitzr    (const unsigned int itrk) const;
  virtual float get_isKtzr     (const unsigned int itrk) const;
  virtual float get_isPtzr     (const unsigned int itrk) const;
  virtual float get_isPintctof (const unsigned int itrk) const;
  virtual float get_isKntctof  (const unsigned int itrk) const;
  virtual float get_isPntctof  (const unsigned int itrk) const;
  virtual short get_tzrecut    (const unsigned int itrk) const;
  virtual int   get_L1Trig     (const unsigned int itrk) const;
  virtual float get_pc1wid     (const unsigned int itrk) const;
  virtual float get_pc2wid     (const unsigned int itrk) const;
  virtual float get_pc3wid     (const unsigned int itrk) const;
  virtual long get_categoryl2eLowPt(const unsigned int itrk) const;
  virtual long get_categoryl2eHighPt(const unsigned int itrk) const;
  virtual short get_candIDl2e(const unsigned int itrk) const;
  virtual int   get_nlvl2MatchLowOcupy(const unsigned int itrk) const;
  virtual int get_RawL1 (const unsigned int itrk) const;
  virtual int get_LivL1 (const unsigned int itrk) const;
  virtual int get_SclL1 (const unsigned int itrk) const;
  virtual float get_tofph1      (const unsigned int itrk) const;
  virtual float get_tofph2      (const unsigned int itrk) const;
  virtual float get_toftdc1     (const unsigned int itrk) const;
  virtual float get_toftdc2     (const unsigned int itrk) const;
  virtual int get_aerindex      (const unsigned int itrk) const;
  virtual int get_aersindex     (const unsigned int itrk) const;
  virtual float get_aerph1      (const unsigned int itrk) const;
  virtual float get_aerph2      (const unsigned int itrk) const;
  virtual float get_aert1       (const unsigned int itrk) const;
  virtual float get_aert2       (const unsigned int itrk) const;
  virtual float get_aernpe      (const unsigned int itrk) const;
  virtual short get_aerstatus   (const unsigned int itrk) const;
  virtual float get_aerph1_0      (const unsigned int itrk) const;
  virtual float get_aerph2_0      (const unsigned int itrk) const;
  virtual float get_aert1_0       (const unsigned int itrk) const;
  virtual float get_aert2_0       (const unsigned int itrk) const;
  virtual float get_aerph1_1      (const unsigned int itrk) const;
  virtual float get_aerph2_1      (const unsigned int itrk) const;
  virtual float get_aert1_1       (const unsigned int itrk) const;
  virtual float get_aert2_1       (const unsigned int itrk) const;
  virtual float get_aerph1_2      (const unsigned int itrk) const;
  virtual float get_aerph2_2      (const unsigned int itrk) const;
  virtual float get_aert1_2       (const unsigned int itrk) const;
  virtual float get_aert2_2       (const unsigned int itrk) const;
  virtual float get_aerph1_3      (const unsigned int itrk) const;
  virtual float get_aerph2_3      (const unsigned int itrk) const;
  virtual float get_aert1_3       (const unsigned int itrk) const;
  virtual float get_aert2_3       (const unsigned int itrk) const;
  virtual int get_aerhitid        (const unsigned int itrk) const;
  virtual int get_aerhitconfig    (const unsigned int itrk) const;
  virtual float get_aersph1_0      (const unsigned int itrk) const;
  virtual float get_aersph2_0      (const unsigned int itrk) const;
  virtual float get_aerst1_0       (const unsigned int itrk) const;
  virtual float get_aerst2_0       (const unsigned int itrk) const;
  virtual float get_aersph1_1      (const unsigned int itrk) const;
  virtual float get_aersph2_1      (const unsigned int itrk) const;
  virtual float get_aerst1_1       (const unsigned int itrk) const;
  virtual float get_aerst2_1       (const unsigned int itrk) const;
  virtual float get_aersph1_2      (const unsigned int itrk) const;
  virtual float get_aersph2_2      (const unsigned int itrk) const;
  virtual float get_aerst1_2       (const unsigned int itrk) const;
  virtual float get_aerst2_2       (const unsigned int itrk) const;
  virtual float get_aersph1_3      (const unsigned int itrk) const;
  virtual float get_aersph2_3      (const unsigned int itrk) const;
  virtual float get_aerst1_3       (const unsigned int itrk) const;
  virtual float get_aerst2_3       (const unsigned int itrk) const;
  virtual int get_aershitid        (const unsigned int itrk) const;
  virtual int get_aershitconfig    (const unsigned int itrk) const;
  virtual float get_tecde       (const unsigned int itrk) const;
  virtual float get_tecde06     (const unsigned int itrk) const;
  virtual float get_tectrklen   (const unsigned int itrk) const;
  virtual short get_tecnde      (const unsigned int itrk) const;
  virtual short get_tecnhit100  (const unsigned int itrk) const;
  virtual short get_tecnhit200  (const unsigned int itrk) const;
  virtual short get_tecnhit50   (const unsigned int itrk) const;
  virtual float get_tecwtb      (const unsigned int itrk) const;
  virtual float get_tecwtbsq    (const unsigned int itrk) const;
  virtual int   get_mcid        (const unsigned int itrk) const;
  virtual int   get_dchid       (const unsigned int itrk) const;
  virtual int   get_emcrawtdc   (const unsigned int itrk) const;
  virtual int   get_emcrawadc   (const unsigned int itrk) const;
  virtual int   get_emcrawadclg (const unsigned int itrk) const;
  virtual float get_Px(const unsigned int itrk) const; // these return pre-calculated Px, Py and Pz;
  virtual float get_Py(const unsigned int itrk) const;
  virtual float get_Pz(const unsigned int itrk) const;
  virtual int   get_idtrk_tof(const unsigned int itrk) const;
  virtual int   get_idtrk_tofw(const unsigned int itrk) const;
  virtual int   get_idtrk_tec(const unsigned int itrk) const;
  virtual int   get_idtrk_crk(const unsigned int itrk) const;
  virtual int   get_idtrk_pc2(const unsigned int itrk) const;
  virtual int   get_idtrk_pc3(const unsigned int itrk) const;
  virtual int   get_idtrk_hbd(const unsigned int itrk) const;
  virtual int   get_idtrk_stof(const unsigned int itrk) const;
  virtual int   get_idtrk_stec(const unsigned int itrk) const;
  virtual int   get_idtrk_scrk(const unsigned int itrk) const;
  virtual int   get_idtrk_spc2(const unsigned int itrk) const;
  virtual int   get_idtrk_spc3(const unsigned int itrk) const;
  virtual float get_hbdhubcharge     (const unsigned int itrk) const;
  virtual float get_hbdspokecharge1  (const unsigned int itrk) const;
  virtual float get_hbdspokecharge2  (const unsigned int itrk) const;
  virtual float get_hbdscharge  (const unsigned int itrk) const;
  virtual float get_hbdlocalmax (const unsigned int itrk) const;

  virtual float get_teccharge       (const unsigned int itrk, const unsigned int iplane) const;
  virtual float get_tecdphiplane    (const unsigned int itrk, const unsigned int iplane) const;
  virtual int   get_tecntimebins    (const unsigned int itrk, const unsigned int iplane) const;
  virtual int   get_tecavgtimebin   (const unsigned int itrk, const unsigned int iplane) const;
  virtual float get_steccharge       (const unsigned int itrk, const unsigned int iplane) const;
  virtual float get_stecdphiplane    (const unsigned int itrk, const unsigned int iplane) const;
  virtual int   get_stecntimebins    (const unsigned int itrk, const unsigned int iplane) const;
  virtual int   get_stecavgtimebin   (const unsigned int itrk, const unsigned int iplane) const;

  // Silicon Vertex (SVX) stuff
  virtual float get_svxdphi (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_svxdz   (const unsigned int itrk, const unsigned int ilayer) const;
  virtual int get_svxid     (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_svxsdphi(const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_svxsdz  (const unsigned int itrk, const unsigned int ilayer) const;
  virtual int get_svxsid    (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_psvxx   (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_psvxy   (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_psvxz   (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_spsvxx  (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_spsvxy  (const unsigned int itrk, const unsigned int ilayer) const;
  virtual float get_spsvxz  (const unsigned int itrk, const unsigned int ilayer) const;
  // entries above are for svx clusters, entries below ate for svx standalone tracks
  virtual int get_svxtrackid           (const unsigned int itrk) const;
  virtual float get_svxtrackquality           (const unsigned int itrk) const; // standalone
  virtual float get_svxdca2d           (const unsigned int itrk) const; // standalone
  virtual float get_svxdca3d           (const unsigned int itrk) const;
  virtual float get_svxdca2dkf         (const unsigned int itrk) const; // KalFit
  virtual float get_svxdca3dkf         (const unsigned int itrk) const;
  // The entries below represent a point of closest approach, and
  // track momentum components ar this point.
  // They are needed for secondary vertex determination for a pair of tracks
  // They come in two flavors: one determined by svx standalone tracking (0)
  // and the second one determined by KalFit (kf)
  virtual float get_svxxyz0              (const unsigned int itrk, const unsigned int icoor) const;
  virtual float get_svxpxyz0             (const unsigned int itrk, const unsigned int icoor) const;
  virtual float get_svxxyzkf             (const unsigned int itrk, const unsigned int icoor) const;
  virtual float get_svxpxyzkf            (const unsigned int itrk, const unsigned int icoor) const;


  // now add a function to determine the PID
  virtual float determine_PIDtof  (const unsigned int /*itrk*/, const float /*m2Centroid*/) const {warning("determine_PIDtof"); return -9999;}
  virtual float determine_PIDemc  (const unsigned int /*itrk*/, const float /*m2Centroid*/) const {warning("determine_PIDemc"); return -9999;}

  //  Fillers...Why are they located here????
  virtual int  set_TClonesArraySize(const unsigned int /*ntrk*/) {return 0;}
  virtual void AddPHParticle       (const unsigned int /*itrk*/) {;}
  virtual PHSnglCentralTrack* AddPHParticle (const unsigned int itrk, const PHSnglCentralTrack &trk);
  virtual PHSnglCentralTrack* AddPHParticle (const PHSnglCentralTrack &trk);
  virtual void RemovePHParticle(const unsigned int itrk);

  //  New methods to simplify manipulations for CabanaBoy
  virtual TObject* GetSingleParticle(unsigned int ipart);
  virtual void AddPHParticle(unsigned int ipart, TObject *o);

  //  New functions that allow for the return of single particles.
  virtual PHSnglCentralTrack* get_track (const unsigned int itrk) const; 
  virtual PHCentralTrack* clone() const;


  // Standard functions of all virtual classes...
  virtual void Reset();
  virtual int isValid() const;
  virtual void identify(std::ostream &os=std::cout) const;
  virtual void ShutUp(const int i = 1);
  virtual void Compress();

 protected:
  virtual TClonesArray *GetTCArray() const {return GetCentral();}
  virtual TClonesArray *GetCentral() const;

 private:
  void warning(const char* field) const;

  ClassDef(PHCentralTrack,1)
};
#endif /* __PHCENTRALTRACK_HH_ */
