/*:>--------------------------------------------------------------------
**: FILE:       mBbcSetGeo.c.template
**: HISTORY:
**:             00jan93-v000a-hpl- Created by stic Version
**:  Id: idl.y,v 1.3 1998/04/20 19:56:35 leitch Exp  
**:<------------------------------------------------------------------*/
#include "mBbcSetGeo.h"
//INCLUDECHECKER: Removed this line: #include "bbc_common.h"
#include "emlLib.h"

//INCLUDECHECKER: Removed this line: #include <cstddef>
#include <string>

int
ds2ReallocTable(TABLE_HEAD_ST** ppHeader, char** ppData, size_t newRowCount);

static short Ringid[] = { 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
                          1, 2, 1, 0, 1, 2, 2, 1, 1, 2,
                          2, 1, 0, 2, 2, 0, 1, 1, 0, 2, 2, 0,
                          0, 2, 2, 0, 1, 1, 0, 2, 2, 0, 
                          1, 2, 2, 1, 1, 2, 2, 1, 0, 1,
                          2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0 };

static short Pmtid[]  = { 5, 6, 4, 5, 7, 3, 4, 6, 8, 2, 
                          3, 4, 7, 9, 2, 3, 5, 8, 1, 2,
                          6, 9, 1, 1, 7,10, 0,10, 0, 0, 8,11,
                         11, 8, 0, 0,10, 0,10, 7, 1, 1, 
                          9, 6, 2, 1, 8, 5, 3, 2, 9, 7, 
                          4, 3, 2, 8, 6, 4, 3, 7, 5, 4, 6, 5 };

long mBbcSetGeo_(
  TABLE_HEAD_ST            *dBbcGeo_h,        DBBCGEO_ST              *dBbcGeo )
{
/*:>--------------------------------------------------------------------
**: ROUTINE:    mBbcSetGeo_
**: DESCRIPTION: Physics Analysis Module ANSI C template.
**:             This is an ANSI C Physics Analysis Module template
**:             automatically generated by stic from mBbcSetGeo.idl.
**:             Please edit comments and code.
**: AUTHOR:     hpl - H.P. Lovecraft, hplovecraft@cthulhu.void
**: ARGUMENTS:
**:       IN:
**:    INOUT:
**:                geo    - PLEASE FILL IN DESCRIPTION HERE
**:               geo_h   - header Structure for geo
**:      OUT:
**: RETURNS:    STAF Condition Value
**:>------------------------------------------------------------------*/

  int i;

   if ( dBbcGeo_h->maxlen < 1 ){ 
     ds2ReallocTable(&dBbcGeo_h,(char**)&dBbcGeo,1); 
   } 

  dBbcGeo_h->nok = 1;

  dBbcGeo->MaxPmtNo = 128;

  for (i=0;i<(dBbcGeo->MaxPmtNo)/2;i++) {
    dBbcGeo->Ring[i] = Ringid[i];
    dBbcGeo->PMT[i]  = Pmtid[i];
  }  
  return STAFCV_OK;
}



