/*:>--------------------------------------------------------------------
**: FILE:       mBbcFEM.c
**: HISTORY:
**:             00jan93-v000a-hpl- Created by stic Version
**:  Id: idl.y,v 1.3 1998/04/20 19:56:35 leitch Exp  
**:<------------------------------------------------------------------*/
#include "mBbcFEM.h"
#include "emlLib.h"

long mBbcFEM_(
  TABLE_HEAD_ST        *dBbcRaw_h,        DBBCRAW_ST          *dBbcRaw ,
  TABLE_HEAD_ST        *dBbcFEM_h,        DBBCFEM_ST          *dBbcFEM )
{
/*:>--------------------------------------------------------------------
**: ROUTINE:    mBbcFEM_
**: DESCRIPTION: Physics Analysis Module ANSI C template.
**:             This is an ANSI C Physics Analysis Module template
**:             automatically generated by stic from mBbcFEM.idl.
**:             Please edit comments and code.
**: AUTHOR:     hpl - H.P. Lovecraft, hplovecraft@cthulhu.void
**: ARGUMENTS:
**:       IN:
**:            dbbcRaw    - PLEASE FILL IN DESCRIPTION HERE
**:           dbbcRaw_h   - header Structure for dbbcRaw
**:        dbbcGhitRaw    - PLEASE FILL IN DESCRIPTION HERE
**:       dbbcGhitRaw_h   - header Structure for dbbcGhitRaw
**:    INOUT:
**:      OUT:
**:            dbbcFEM    - PLEASE FILL IN DESCRIPTION HERE
**:           dbbcFEM_h   - header Structure for dbbcFEM
**: RETURNS:    STAF Condition Value
**:>------------------------------------------------------------------*/
    long  i;
    short islot;
    short index0;
    short nFEMdata = 25;
    unsigned short event = 0x1234;

    DBBCRAW_ST *rawp;  /* working pointer of Raw Data */

/* Sanity check of header for table "dBbcRaw"... */
    if( ( dBbcRaw_h->maxlen <= 0 ) ||
       ( dBbcRaw_h->nok > dBbcRaw_h->maxlen ) ){
       return STAFCV_BAD;
    }
    if( ( dBbcFEM_h->maxlen <= 0 ) ||
       ( dBbcFEM_h->nok > dBbcFEM_h->maxlen ) ){
       return STAFCV_BAD;
    }

    /* CFM: the actual size of dBbcFEM was never set?? */
    dBbcFEM_h->nok = 1;    /*  set by CFM, September 12, 1998    */
                           /*  correct by HO, September 14, 1998 */

    /* Headers */
    dBbcFEM->CAV1     = 0xFFFF;
    dBbcFEM->det      = 0x0001;
    dBbcFEM->Ecounter = event;
    dBbcFEM->adr      = 0x1000;
    dBbcFEM->Flag     = 0; /* I don't know the UserWord from ArcNet */
    dBbcFEM->Bcounter = 0; /* I don't know the beam clock counter */

    dBbcFEM->parity   = 0x0953; /* I don't know the parity word */
    dBbcFEM->CAV2     = 0x0000;

    /* Loop through FEM and fill header of FEM data */

    for (islot=0;islot<16;islot++) {
      index0 = islot*nFEMdata;
      dBbcFEM->Word[index0]   = islot+1;   /* FEM board Number */
    }

    for (i=0; i<dBbcRaw_h->nok; i++){ /* Loop of raw data */

      short imodule;
      rawp=dBbcRaw+i;

      index0 = ((rawp->Pmt)/8)*nFEMdata; /*nFEMdata = 25*/
      imodule= (rawp->Pmt)/8;
/**** 
      dBbcFEM->Word[index0+1+(i-(imodule)*8)*3] = rawp->Adc; 
      dBbcFEM->Word[index0+2+(i-(imodule)*8)*3] = rawp->Tdc0; 
      dBbcFEM->Word[index0+3+(i-(imodule)*8)*3] = rawp->Tdc1; 
****/
      dBbcFEM->Word[index0+1+(i-(imodule)*8)*3] = rawp->Tdc0; 
      dBbcFEM->Word[index0+2+(i-(imodule)*8)*3] = rawp->Tdc1; 
      dBbcFEM->Word[index0+3+(i-(imodule)*8)*3] = rawp->Adc; 
    }

/*
    printf("cav1      = %4x\n",dBbcFEM->CAV1);
    printf("det       = %4x\n",dBbcFEM->det);
    printf("Ecounter  = %4x\n",dBbcFEM->Ecounter);
    printf("adr       = %4x\n",dBbcFEM->adr);
    printf("Flag      = %4x\n",dBbcFEM->Flag);
    printf("Bcounter  = %4x\n",dBbcFEM->Bcounter);

    for (i=0; i<419; i++) {
      printf("word[%3d] = %4x\n",i,dBbcFEM->Word[i]);
    } 

    printf("parity    = %4x\n",dBbcFEM->parity);
    printf("cav2      = %4x\n",dBbcFEM->CAV2);
*/   
    return STAFCV_OK;

}
