#include <strstream>

TH1F *h[5120];
int nhist = 5120;

merge_9591_11291 (const char *ofname="merge9591_11291.root") {
  void add_h1 (char*);
  TFile *outfile = TFile::Open (ofname, "recreate", "no_field", 1);

  int i;
  for(i=0;i<nhist;i++) {
    strstream sname;
    sname << "sADC" << i;
    h[i] = new TH1F (sname.str(),sname.str(),256,-100.,1024.);
    //    cout << sname.str() << "is created" <<endl;
  }

  add_h1("HISTOS/run9591_online_monitor_histos.root");
  add_h1("HISTOS/run9598_online_monitor_histos.root");
  add_h1("HISTOS/run9607_online_monitor_histos.root");
  add_h1("HISTOS/run9613_online_monitor_histos.root");
  add_h1("HISTOS/run9666_online_monitor_histos.root");
  add_h1("HISTOS/run9670_online_monitor_histos.root");
  add_h1("HISTOS/run9678_online_monitor_histos.root");
  add_h1("HISTOS/run9685_online_monitor_histos.root");
  add_h1("HISTOS/run9691_online_monitor_histos.root");
  add_h1("HISTOS/run9695_online_monitor_histos.root");
  add_h1("HISTOS/run9703_online_monitor_histos.root");
  add_h1("HISTOS/run9712_online_monitor_histos.root");
  add_h1("HISTOS/run9720_online_monitor_histos.root");
  add_h1("HISTOS/run9724_online_monitor_histos.root");
  add_h1("HISTOS/run9729_online_monitor_histos.root");
  add_h1("HISTOS/run9739_online_monitor_histos.root");
  add_h1("HISTOS/run9741_online_monitor_histos.root");
  add_h1("HISTOS/run9746_online_monitor_histos.root");
  add_h1("HISTOS/run9750_online_monitor_histos.root");
  add_h1("HISTOS/run9752_online_monitor_histos.root");
  add_h1("HISTOS/run9757_online_monitor_histos.root");
  add_h1("HISTOS/run9759_online_monitor_histos.root");
  add_h1("HISTOS/run9770_online_monitor_histos.root");
  add_h1("HISTOS/run9839_online_monitor_histos.root");
  add_h1("HISTOS/run9844_online_monitor_histos.root");
  add_h1("HISTOS/run9847_online_monitor_histos.root");
  add_h1("HISTOS/run9851_online_monitor_histos.root");
  add_h1("HISTOS/run9858_online_monitor_histos.root");
  add_h1("HISTOS/run9862_online_monitor_histos.root");
  add_h1("HISTOS/run9889_online_monitor_histos.root");
  add_h1("HISTOS/run9890_online_monitor_histos.root");
  add_h1("HISTOS/run9923_online_monitor_histos.root");
  add_h1("HISTOS/run9939_online_monitor_histos.root");
  add_h1("HISTOS/run9942_online_monitor_histos.root");
  add_h1("HISTOS/run9944_online_monitor_histos.root");
  add_h1("HISTOS/run9948_online_monitor_histos.root");
  add_h1("HISTOS/run9972_online_monitor_histos.root");
  add_h1("HISTOS/run9978_online_monitor_histos.root");
  add_h1("HISTOS/run9979_online_monitor_histos.root");
  add_h1("HISTOS/run9981_online_monitor_histos.root");
  add_h1("HISTOS/run9987_online_monitor_histos.root");
  add_h1("HISTOS/run9988_online_monitor_histos.root");
  add_h1("HISTOS/run9992_online_monitor_histos.root");
  add_h1("HISTOS/run10000_online_monitor_histos.root");
  add_h1("HISTOS/run10003_online_monitor_histos.root");
  add_h1("HISTOS/run10008_online_monitor_histos.root");
  add_h1("HISTOS/run10014_online_monitor_histos.root");
  add_h1("HISTOS/run10017_online_monitor_histos.root");
  add_h1("HISTOS/run10025_online_monitor_histos.root");
  add_h1("HISTOS/run10028_online_monitor_histos.root");
  add_h1("HISTOS/run10030_online_monitor_histos.root");
  add_h1("HISTOS/run10039_online_monitor_histos.root");
  add_h1("HISTOS/run10042_online_monitor_histos.root");
  add_h1("HISTOS/run10047_online_monitor_histos.root");
  add_h1("HISTOS/run10102_online_monitor_histos.root");
  add_h1("HISTOS/run10108_online_monitor_histos.root");
  add_h1("HISTOS/run10111_online_monitor_histos.root");
  add_h1("HISTOS/run10113_online_monitor_histos.root");
  add_h1("HISTOS/run10115_online_monitor_histos.root");
  add_h1("HISTOS/run10121_online_monitor_histos.root");
  add_h1("HISTOS/run10126_online_monitor_histos.root");
  add_h1("HISTOS/run10146_online_monitor_histos.root");
  add_h1("HISTOS/run10152_online_monitor_histos.root");
  add_h1("HISTOS/run10156_online_monitor_histos.root");
  add_h1("HISTOS/run10162_online_monitor_histos.root");
  add_h1("HISTOS/run10164_online_monitor_histos.root");
  add_h1("HISTOS/run10167_online_monitor_histos.root");
  add_h1("HISTOS/run10169_online_monitor_histos.root");
  add_h1("HISTOS/run10171_online_monitor_histos.root");
  add_h1("HISTOS/run10205_online_monitor_histos.root");
  add_h1("HISTOS/run10213_online_monitor_histos.root");
  add_h1("HISTOS/run10215_online_monitor_histos.root");
  add_h1("HISTOS/run10218_online_monitor_histos.root");
  add_h1("HISTOS/run10221_online_monitor_histos.root");
  add_h1("HISTOS/run10226_online_monitor_histos.root");
  add_h1("HISTOS/run10232_online_monitor_histos.root");
  add_h1("HISTOS/run10238_online_monitor_histos.root");
  add_h1("HISTOS/run10242_online_monitor_histos.root");
  add_h1("HISTOS/run10243_online_monitor_histos.root");
  add_h1("HISTOS/run10245_online_monitor_histos.root");
  add_h1("HISTOS/run10248_online_monitor_histos.root");
  add_h1("HISTOS/run10251_online_monitor_histos.root");
  add_h1("HISTOS/run10254_online_monitor_histos.root");
  add_h1("HISTOS/run10257_online_monitor_histos.root");
  add_h1("HISTOS/run10259_online_monitor_histos.root");
  add_h1("HISTOS/run10263_online_monitor_histos.root");
  add_h1("HISTOS/run10271_online_monitor_histos.root");
  add_h1("HISTOS/run10277_online_monitor_histos.root");
  add_h1("HISTOS/run10289_online_monitor_histos.root");
  add_h1("HISTOS/run10302_online_monitor_histos.root");
  add_h1("HISTOS/run10307_online_monitor_histos.root");
  add_h1("HISTOS/run10311_online_monitor_histos.root");
  add_h1("HISTOS/run10316_online_monitor_histos.root");
  add_h1("HISTOS/run10320_online_monitor_histos.root");
  add_h1("HISTOS/run10327_online_monitor_histos.root");
  add_h1("HISTOS/run10329_online_monitor_histos.root");
  add_h1("HISTOS/run10331_online_monitor_histos.root");
  add_h1("HISTOS/run10337_online_monitor_histos.root");
  add_h1("HISTOS/run10344_online_monitor_histos.root");
  add_h1("HISTOS/run10349_online_monitor_histos.root");
  add_h1("HISTOS/run10351_online_monitor_histos.root");
  add_h1("HISTOS/run10353_online_monitor_histos.root");
  add_h1("HISTOS/run10358_online_monitor_histos.root");
  add_h1("HISTOS/run10360_online_monitor_histos.root");
  add_h1("HISTOS/run10362_online_monitor_histos.root");
  add_h1("HISTOS/run10364_online_monitor_histos.root");
  add_h1("HISTOS/run10427_online_monitor_histos.root");
  add_h1("HISTOS/run10429_online_monitor_histos.root");
  add_h1("HISTOS/run10433_online_monitor_histos.root");
  add_h1("HISTOS/run10436_online_monitor_histos.root");
  add_h1("HISTOS/run10437_online_monitor_histos.root");
  add_h1("HISTOS/run10439_online_monitor_histos.root");
  add_h1("HISTOS/run10441_online_monitor_histos.root");
  add_h1("HISTOS/run10505_online_monitor_histos.root");
  add_h1("HISTOS/run10507_online_monitor_histos.root");
  add_h1("HISTOS/run10510_online_monitor_histos.root");
  add_h1("HISTOS/run10515_online_monitor_histos.root");
  add_h1("HISTOS/run10523_online_monitor_histos.root");
  add_h1("HISTOS/run10525_online_monitor_histos.root");
  add_h1("HISTOS/run10527_online_monitor_histos.root");
  add_h1("HISTOS/run10545_online_monitor_histos.root");
  add_h1("HISTOS/run10603_online_monitor_histos.root");
  add_h1("HISTOS/run10629_online_monitor_histos.root");
  add_h1("HISTOS/run10643_online_monitor_histos.root");
  add_h1("HISTOS/run10645_online_monitor_histos.root");
  add_h1("HISTOS/run10647_online_monitor_histos.root");
  add_h1("HISTOS/run10651_online_monitor_histos.root");
  add_h1("HISTOS/run10679_online_monitor_histos.root");
  add_h1("HISTOS/run10700_online_monitor_histos.root");
  add_h1("HISTOS/run10706_online_monitor_histos.root");
  add_h1("HISTOS/run10708_online_monitor_histos.root");
  add_h1("HISTOS/run10726_online_monitor_histos.root");
  add_h1("HISTOS/run10728_online_monitor_histos.root");
  add_h1("HISTOS/run10730_online_monitor_histos.root");
  add_h1("HISTOS/run10732_online_monitor_histos.root");
  add_h1("HISTOS/run10734_online_monitor_histos.root");
  add_h1("HISTOS/run10736_online_monitor_histos.root");
  add_h1("HISTOS/run10738_online_monitor_histos.root");
  add_h1("HISTOS/run10740_online_monitor_histos.root");
  add_h1("HISTOS/run10742_online_monitor_histos.root");
  add_h1("HISTOS/run10744_online_monitor_histos.root");
  add_h1("HISTOS/run10747_online_monitor_histos.root");
  add_h1("HISTOS/run10749_online_monitor_histos.root");
  add_h1("HISTOS/run10751_online_monitor_histos.root");
  add_h1("HISTOS/run10758_online_monitor_histos.root");
  add_h1("HISTOS/run10761_online_monitor_histos.root");
  add_h1("HISTOS/run10763_online_monitor_histos.root");
  add_h1("HISTOS/run10765_online_monitor_histos.root");
  add_h1("HISTOS/run10767_online_monitor_histos.root");
  add_h1("HISTOS/run11285_online_monitor_histos.root");
  add_h1("HISTOS/run11289_online_monitor_histos.root");
  add_h1("HISTOS/run11291_online_monitor_histos.root");
  
  outfile->Write();
  outfile->Close();
  delete outfile;
  
}

void add_h1(char *fname) {
  tf = new TFile(fname);
  int i;
  for(i=0;i<nhist;i++) {
    strstream hname;
    hname << "ADC" << i;
    h[i]->Add((TH1F*)tf->Get(hname.str()));
  }
  cout << "file "<<fname<<" is added" << endl;
  delete tf;
}
