//-----------------------------------------------------------------------------
//
//  Root LinkDef file for class TofTrkTree
//
//  Author: auto-generated by PdbRootify.pl
//-----------------------------------------------------------------------------
#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class TofTrkTree-!;

#endif /* __CINT__ */
