//-----------------------------------------------------------------------------
//
//  The pdbcal package
//  Copyright (C) PHENIX collaboration, 1999
//
//  Root LinkDef file for class TreeToNtpl
//
//  Author: auto-generated by PdbRootify.pl
//-----------------------------------------------------------------------------
#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class TreeToNtpl-!;

#endif /* __CINT__ */
