void printall(const char *histIFile="dstcheck.root"){
c1 = new TCanvas("c1","DST QA canvas",200,10,700,700);
c1->SetFillColor(0);
f= new TFile(histIFile);
bbct0->Draw(); 
c1->Print("bbct0.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait bbct0.ps"); 
gSystem->Exec("ppmtogif  bbct0001.ppm >.//bbct0.gif"); 
bbcvtx->Draw(); 
c1->Print("bbcvtx.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait bbcvtx.ps"); 
gSystem->Exec("ppmtogif  bbcvtx001.ppm >.//bbcvtx.gif"); 
bbcnpmt->Draw(); 
c1->Print("bbcnpmt.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait bbcnpmt.ps"); 
gSystem->Exec("ppmtogif  bbcnpmt001.ppm >.//bbcnpmt.gif"); 
bbcQnQs->Draw(); 
c1->Print("bbcQnQs.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait bbcQnQs.ps"); 
gSystem->Exec("ppmtogif  bbcQnQs001.ppm >.//bbcQnQs.gif"); 
bbcvtxt0->Draw(); 
c1->Print("bbcvtxt0.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait bbcvtxt0.ps"); 
gSystem->Exec("ppmtogif  bbcvtxt0001.ppm >.//bbcvtxt0.gif"); 
f->cd(); 
dchHitDistanceW->Draw(); 
c1->Print("dchHitDistanceW.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchHitDistanceW.ps"); 
gSystem->Exec("ppmtogif  dchHitDistanceW001.ppm >.//dchHitDistanceW.gif"); 
dchHitDistanceE->Draw(); 
c1->Print("dchHitDistanceE.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchHitDistanceE.ps"); 
gSystem->Exec("ppmtogif  dchHitDistanceE001.ppm >.//dchHitDistanceE.gif"); 
dchTrkMult->Draw(); 
c1->Print("dchTrkMult.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkMult.ps"); 
gSystem->Exec("ppmtogif  dchTrkMult001.ppm >.//dchTrkMult.gif"); 
dchTrkVHitsW->Draw(); 
c1->Print("dchTrkVHitsW.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkVHitsW.ps"); 
gSystem->Exec("ppmtogif  dchTrkVHitsW001.ppm >.//dchTrkVHitsW.gif"); 
dchTrkVHitsE->Draw(); 
c1->Print("dchTrkVHitsE.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkVHitsE.ps"); 
gSystem->Exec("ppmtogif  dchTrkVHitsE001.ppm >.//dchTrkVHitsE.gif"); 
dchTrkWVE->Draw(); 
c1->Print("dchTrkWVE.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkWVE.ps"); 
gSystem->Exec("ppmtogif  dchTrkWVE001.ppm >.//dchTrkWVE.gif"); 
dchTrkAlpha->Draw(); 
c1->Print("dchTrkAlpha.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkAlpha.ps"); 
gSystem->Exec("ppmtogif  dchTrkAlpha001.ppm >.//dchTrkAlpha.gif"); 
dchTrkMom->Draw(); 
c1->Print("dchTrkMom.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkMom.ps"); 
gSystem->Exec("ppmtogif  dchTrkMom001.ppm >.//dchTrkMom.gif"); 
dchTrkPhi->Draw(); 
c1->Print("dchTrkPhi.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkPhi.ps"); 
gSystem->Exec("ppmtogif  dchTrkPhi001.ppm >.//dchTrkPhi.gif"); 
dchTrkBeta->Draw(); 
c1->Print("dchTrkBeta.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkBeta.ps"); 
gSystem->Exec("ppmtogif  dchTrkBeta001.ppm >.//dchTrkBeta.gif"); 
dchTrkQuality->Draw(); 
c1->Print("dchTrkQuality.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkQuality.ps"); 
gSystem->Exec("ppmtogif  dchTrkQuality001.ppm >.//dchTrkQuality.gif"); 
dchTrkNHits->Draw(); 
c1->Print("dchTrkNHits.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkNHits.ps"); 
gSystem->Exec("ppmtogif  dchTrkNHits001.ppm >.//dchTrkNHits.gif"); 
dchTrkDist->Draw(); 
c1->Print("dchTrkDist.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchTrkDist.ps"); 
gSystem->Exec("ppmtogif  dchTrkDist001.ppm >.//dchTrkDist.gif"); 
dchGoodEvent->Draw(); 
c1->Print("dchGoodEvent.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait dchGoodEvent.ps"); 
gSystem->Exec("ppmtogif  dchGoodEvent001.ppm >.//dchGoodEvent.gif"); 
f->cd(); 
emcWestETot->Draw(); 
c1->Print("emcWestETot.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcWestETot.ps"); 
gSystem->Exec("ppmtogif  emcWestETot001.ppm >.//emcWestETot.gif"); 
emcEastETot->Draw(); 
c1->Print("emcEastETot.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcEastETot.ps"); 
gSystem->Exec("ppmtogif  emcEastETot001.ppm >.//emcEastETot.gif"); 
emcWestE->Draw(); 
c1->Print("emcWestE.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcWestE.ps"); 
gSystem->Exec("ppmtogif  emcWestE001.ppm >.//emcWestE.gif"); 
emcEastE->Draw(); 
c1->Print("emcEastE.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcEastE.ps"); 
gSystem->Exec("ppmtogif  emcEastE001.ppm >.//emcEastE.gif"); 
emcWestE1->Draw(); 
c1->Print("emcWestE1.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcWestE1.ps"); 
gSystem->Exec("ppmtogif  emcWestE1001.ppm >.//emcWestE1.gif"); 
emcEastE1->Draw(); 
c1->Print("emcEastE1.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcEastE1.ps"); 
gSystem->Exec("ppmtogif  emcEastE1001.ppm >.//emcEastE1.gif"); 
emcWestTime->Draw(); 
c1->Print("emcWestTime.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcWestTime.ps"); 
gSystem->Exec("ppmtogif  emcWestTime001.ppm >.//emcWestTime.gif"); 
emcEastTime->Draw(); 
c1->Print("emcEastTime.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcEastTime.ps"); 
gSystem->Exec("ppmtogif  emcEastTime001.ppm >.//emcEastTime.gif"); 
emcE1YZ->Draw(); 
c1->Print("emcE1YZ.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcE1YZ.ps"); 
gSystem->Exec("ppmtogif  emcE1YZ001.ppm >.//emcE1YZ.gif"); 
emcW0YZ->Draw(); 
c1->Print("emcW0YZ.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcW0YZ.ps"); 
gSystem->Exec("ppmtogif  emcW0YZ001.ppm >.//emcW0YZ.gif"); 
emcW1YZ->Draw(); 
c1->Print("emcW1YZ.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait emcW1YZ.ps"); 
gSystem->Exec("ppmtogif  emcW1YZ001.ppm >.//emcW1YZ.gif"); 
f->cd();
MutSPulseSamples->Draw();
c1->Print("MutSPulseSamples.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSPulseSamples.ps"); 
gSystem->Exec("ppmtogif  MutSPulseSamples001.ppm >.//MutSPulseSamples.gif");
MutSCathClustWidth->Draw();
c1->Print("MutSCathClusWidth.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusWidth.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusWidth001.ppm >.//MutSCathClusWidth.gif");
MutSCathClustQFit->Draw();
c1->Print("MutSCathClusQFit.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQFit.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQFit001.ppm >.//MutSCathClusQFit.gif");
MutSCathClustQFitSt1->Draw();
c1->Print("MutSCathClusQFitSt1.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQFitSt1.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQFitSt1001.ppm >.//MutSCathClusQFitSt1.gif");
MutSCathClustQFitSt2->Draw();
c1->Print("MutSCathClusQFitSt2.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQFitSt2.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQFitSt2001.ppm >.//MutSCathClusQFitSt2.gif");
MutSCathClustQFitSt3->Draw();
c1->Print("MutSCathClusQFitSt3.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQFitSt3.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQFitSt3001.ppm >.//MutSCathClusQFitSt3.gif");
MutSCathClustQPeak->Draw();
c1->Print("MutSCathClusQPeak.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQPeak.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQPeak001.ppm >.//MutSCathClusQPeak.gif");
MutSCathClustQPeakSt1->Draw();
c1->Print("MutSCathClusQPeakSt1.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQPeakSt1.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQPeakSt1001.ppm >.//MutSCathClusQPeakSt1.gif");
MutSCathClustQPeakSt2->Draw();
c1->Print("MutSCathClusQPeakSt2.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQPeakSt2.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQPeakSt2001.ppm >.//MutSCathClusQPeakSt2.gif");
MutSCathClustQPeakSt3->Draw();
c1->Print("MutSCathClusQPeakSt3.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSCathClusQPeakSt3.ps"); 
gSystem->Exec("ppmtogif  MutSCathClusQPeakSt3001.ppm >.//MutSCathClusQPeakSt3.gif");
MutSNumCathClustersSt1->Draw();
c1->Print("MutSNumCathClustersSt1.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSNumCathClustersSt1.ps"); 
gSystem->Exec("ppmtogif  MutSNumCathClustersSt1001.ppm >.//MutSNumCathClustersSt1.gif");
MutSNumCathClustersSt2->Draw();
c1->Print("MutSNumCathClustersSt2.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSNumCathClustersSt2.ps"); 
gSystem->Exec("ppmtogif  MutSNumCathClustersSt2001.ppm >.//MutSNumCathClustersSt2.gif");
MutSNumCathClustersSt3->Draw();
c1->Print("MutSNumCathClustersSt3.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSNumCathClustersSt3.ps"); 
gSystem->Exec("ppmtogif  MutSNumCathClustersSt3001.ppm >.//MutSNumCathClustersSt3.gif");
MutSHitsPerPlaneSt1->Draw();
c1->Print("MutSHitsPerPlaneSt1.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSHitsPerPlaneSt1.ps"); 
gSystem->Exec("ppmtogif  MutSHitsPerPlaneSt1001.ppm >.//MutSHitsPerPlaneSt1.gif");
MutSHitsPerPlaneSt2->Draw();
c1->Print("MutSHitsPerPlaneSt2.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSHitsPerPlaneSt2.ps"); 
gSystem->Exec("ppmtogif  MutSHitsPerPlaneSt2001.ppm >.//MutSHitsPerPlaneSt2.gif");
MutSHitsPerPlaneSt3->Draw();
c1->Print("MutSHitsPerPlaneSt3.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSHitsPerPlaneSt3.ps"); 
gSystem->Exec("ppmtogif  MutSHitsPerPlaneSt3001.ppm >.//MutSHitsPerPlaneSt3.gif");
c1->SetLogy(1);
MutSNumTracks->Draw();
c1->Print("MutSNumTracks.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSNumTracks.ps"); 
gSystem->Exec("ppmtogif  MutSNumTracks001.ppm >.//MutSNumTracks.gif");
c1->SetLogy(0);
MutSTrackMom->Draw();
c1->Print("MutSMeanTrackMom.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait MutSMeanTrackMom.ps"); 
gSystem->Exec("ppmtogif  MutSMeanTrackMom001.ppm >.//MutSMeanTrackMom.gif");
f->cd();
pc1EastThetaPhi->Draw(); 
c1->Print("pc1EastThetaPhi.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc1EastThetaPhi.ps"); 
gSystem->Exec("ppmtogif  pc1EastThetaPhi001.ppm >.//pc1EastThetaPhi.gif"); 
pc1EastActivity->Draw(); 
c1->Print("pc1EastActivity.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc1EastActivity.ps"); 
gSystem->Exec("ppmtogif  pc1EastActivity001.ppm >.//pc1EastActivity.gif"); 
pc1EastRatio->Draw(); 
c1->Print("pc1EastRatio.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc1EastRatio.ps"); 
gSystem->Exec("ppmtogif  pc1EastRatio001.ppm >.//pc1EastRatio.gif"); 
pc1WestThetaPhi->Draw(); 
c1->Print("pc1WestThetaPhi.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc1WestThetaPhi.ps"); 
gSystem->Exec("ppmtogif  pc1WestThetaPhi001.ppm >.//pc1WestThetaPhi.gif"); 
pc1WestActivity->Draw(); 
c1->Print("pc1WestActivity.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc1WestActivity.ps"); 
gSystem->Exec("ppmtogif  pc1WestActivity001.ppm >.//pc1WestActivity.gif"); 
pc1WestRatio->Draw(); 
c1->Print("pc1WestRatio.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc1WestRatio.ps"); 
gSystem->Exec("ppmtogif  pc1WestRatio001.ppm >.//pc1WestRatio.gif"); 
pc2WestThetaPhi->Draw(); 
c1->Print("pc2WestThetaPhi.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc2WestThetaPhi.ps"); 
gSystem->Exec("ppmtogif  pc2WestThetaPhi001.ppm >.//pc2WestThetaPhi.gif"); 
pc2WestActivity->Draw(); 
c1->Print("pc2WestActivity.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc2WestActivity.ps"); 
gSystem->Exec("ppmtogif  pc2WestActivity001.ppm >.//pc2WestActivity.gif"); 
pc2WestRatio->Draw(); 
c1->Print("pc2WestRatio.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc2WestRatio.ps"); 
gSystem->Exec("ppmtogif  pc2WestRatio001.ppm >.//pc2WestRatio.gif"); 
pc3EastThetaPhi->Draw(); 
c1->Print("pc3EastThetaPhi.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc3EastThetaPhi.ps"); 
gSystem->Exec("ppmtogif  pc3EastThetaPhi001.ppm >.//pc3EastThetaPhi.gif"); 
pc3EastActivity->Draw(); 
c1->Print("pc3EastActivity.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc3EastActivity.ps"); 
gSystem->Exec("ppmtogif  pc3EastActivity001.ppm >.//pc3EastActivity.gif"); 
pc3EastRatio->Draw(); 
c1->Print("pc3EastRatio.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc3EastRatio.ps"); 
gSystem->Exec("ppmtogif  pc3EastRatio001.ppm >.//pc3EastRatio.gif"); 
pc3WestThetaPhi->Draw(); 
c1->Print("pc3WestThetaPhi.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc3WestThetaPhi.ps"); 
gSystem->Exec("ppmtogif  pc3WestThetaPhi001.ppm >.//pc3WestThetaPhi.gif"); 
pc3WestActivity->Draw(); 
c1->Print("pc3WestActivity.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc3WestActivity.ps"); 
gSystem->Exec("ppmtogif  pc3WestActivity001.ppm >.//pc3WestActivity.gif"); 
pc3WestRatio->Draw(); 
c1->Print("pc3WestRatio.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait pc3WestRatio.ps"); 
gSystem->Exec("ppmtogif  pc3WestRatio001.ppm >.//pc3WestRatio.gif"); 
f->cd(); 
tecTrkMult->Draw(); 
c1->Print("tecTrkMult.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tecTrkMult.ps"); 
gSystem->Exec("ppmtogif  tecTrkMult001.ppm >.//tecTrkMult.gif"); 
tecTrkNhits->Draw(); 
c1->Print("tecTrkNhits.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tecTrkNhits.ps"); 
gSystem->Exec("ppmtogif  tecTrkNhits001.ppm >.//tecTrkNhits.gif"); 
tecYvsX->Draw(); 
c1->Print("tecYvsX.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tecYvsX.ps"); 
gSystem->Exec("ppmtogif  tecYvsX001.ppm >.//tecYvsX.gif"); 
tecNhitProf->Draw(); 
c1->Print("tecNhitProf.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tecNhitProf.ps"); 
gSystem->Exec("ppmtogif  tecNhitProf001.ppm >.//tecNhitProf.gif"); 
tecNtrkProf->Draw(); 
c1->Print("tecNtrkProf.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tecNtrkProf.ps"); 
gSystem->Exec("ppmtogif  tecNtrkProf001.ppm >.//tecNtrkProf.gif"); 
f->cd(); 
tofDist->Draw(); 
c1->Print("tofDist.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofDist.ps"); 
gSystem->Exec("ppmtogif  tofDist001.ppm >.//tofDist.gif"); 
tofELoss->Draw(); 
c1->Print("tofELoss.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofELoss.ps"); 
gSystem->Exec("ppmtogif  tofELoss001.ppm >.//tofELoss.gif"); 
tofYZ->Draw(); 
c1->Print("tofYZ.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofYZ.ps"); 
gSystem->Exec("ppmtogif  tofYZ001.ppm >.//tofYZ.gif"); 
tofYX->Draw(); 
c1->Print("tofYX.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofYX.ps"); 
gSystem->Exec("ppmtogif  tofYX001.ppm >.//tofYX.gif"); 
tofProY->Draw(); 
c1->Print("tofProY.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofProY.ps"); 
gSystem->Exec("ppmtogif  tofProY001.ppm >.//tofProY.gif"); 
tofProZ->Draw(); 
c1->Print("tofProZ.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofProZ.ps"); 
gSystem->Exec("ppmtogif  tofProZ001.ppm >.//tofProZ.gif"); 
tofBetaPt->Draw(); 
c1->Print("tofBetaPt.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofBetaPt.ps"); 
gSystem->Exec("ppmtogif  tofBetaPt001.ppm >.//tofBetaPt.gif"); 
tofMass2p->Draw(); 
c1->Print("tofMass2p.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait tofMass2p.ps"); 
gSystem->Exec("ppmtogif  tofMass2p001.ppm >.//tofMass2p.gif"); 
f->cd(); 
zdcenorth->Draw(); 
c1->Print("zdcenorth.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait zdcenorth.ps"); 
gSystem->Exec("ppmtogif  zdcenorth001.ppm >.//zdcenorth.gif"); 
zdcesouth->Draw(); 
c1->Print("zdcesouth.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait zdcesouth.ps"); 
gSystem->Exec("ppmtogif  zdcesouth001.ppm >.//zdcesouth.gif"); 
zdcesum->Draw(); 
c1->Print("zdcesum.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait zdcesum.ps"); 
gSystem->Exec("ppmtogif  zdcesum001.ppm >.//zdcesum.gif"); 
zdcEnEs->Draw(); 
c1->Print("zdcEnEs.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait zdcEnEs.ps"); 
gSystem->Exec("ppmtogif  zdcEnEs001.ppm >.//zdcEnEs.gif"); 
zdcvtx->Draw(); 
c1->Print("zdcvtx.ps","eps"); 
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait zdcvtx.ps"); 
gSystem->Exec("ppmtogif  zdcvtx001.ppm >.//zdcvtx.gif"); 
f->cd();
muiNHits->Draw();
c1->Print("muiNHits.ps","eps");
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait muiNHits.ps"); 
gSystem->Exec("ppmtogif  muiNHits001.ppm >.//muiNHits.gif");
muiNRoads->Draw();
c1->Print("muiNRoads.ps","eps");
gSystem->Exec("pstopnm -ppm -xborder 0 -yborder 0 -portrait muiNRoads.ps");
gSystem->Exec("ppmtogif  muiNRoads001.ppm >.//muiNRoads.gif");
f->cd();
gSystem->Exec("rm *.ppm"); 
gSystem->Exec("rm *.ps"); 
} 

