c $Id: gcmzfo.inc,v 1.2 2008/05/21 08:15:54 hpereira Exp $

c     COMMON/GCMZFO/IOMATE,IOPART,IOTMED,IOSEJD,IOSJDD,IOSJDH,IOSTAK
c      +             ,IOMZFO(13)

c       INTEGER       IOMATE,IOPART,IOTMED,IOSEJD,IOSJDD,IOSJDH,IOSTAK
c      +             ,IOMZFO


c using official geant321 headers in place of local hacks
c to avoid conflicts when changing geant version
#include "geant321/gcmzfo.inc"
