c
c      WIS version of HBD
c
      common/hbdgeompar/ hbdg_rin, hbdg_rout, hbdg_dz,
     &  shade_in, shade_height, shade_spacing_x, shade_spacing_y,	 
     &  mylar_th, g10_th, g10_fr_x, g10_fr_y, g10_fr_z,
     &  g10_fr_1, g10_fr_2, g10_fr_3, g10_fr_4,
     &  g10_fr_5, g10_fr_6, g10_fr_7, g10_fr_8, g10_fr_9,
     &  g10_fr_10,
     &  hex_th, mylar_w_th, nitr_th,
     &  g10_gem_fr, g10_electr, gem_size, gem_spacer,
     &  copper_th, gem_dist, capton_th, gem_box,
     &  irot_hbd
      
      Real hbdg_rin, hbdg_rout, hbdg_dz,
     &  mylar_th, g10_th, g10_fr_x, g10_fr_y, g10_fr_z,
     &  g10_fr_1, g10_fr_2, g10_fr_3, g10_fr_4,
     &  g10_fr_5, g10_fr_6, g10_fr_7, g10_fr_8, g10_fr_9,
     &  g10_fr_10,
     &  hex_th, mylar_w_th, nitr_th,
     &  g10_gem_fr, g10_electr, gem_size, gem_spacer,
     &  copper_th, gem_dist, capton_th, gem_box
      Integer irot_hbd
      
      Real shade_height, shade_spacing_x, shade_spacing_y
      Integer shade_in

