
	common/tpcgeompar/ tpcg_Rin, tpcg_Rout, tpcg_R1, 
     >   tpcg_R2, tpcg_dz, tpcg_dzm, tpcg_dzpr, tpcg_A_th, 
     >   tpcg_C_th, tpcg_Si_th, nmpadrow,
     >   y_shift_act, dx_spt, dz_spt, mgas_z_shift, mgas_w_shift,
     >   R_tpc_pos, tpc_Z_pos, tpcmod_dx1, tpcmod_dx2, tpcmod_dy,
     >   tpcmod_dz, Rch, Rptc, ddr, dx_add, pi_4, pi_8,
     >   dr_mlrth, dz_mlrth, dr_gap, dz_gap

	 Real tpcg_Rin, tpcg_Rout, tpcg_R1, 
     >   tpcg_R2, tpcg_dz, tpcg_dzm, tpcg_dzpr, tpcg_A_th, 
     >   tpcg_C_th, tpcg_Si_th,
     >   y_shift_act, dx_spt, dz_spt, mgas_z_shift, mgas_w_shift,
     >   R_tpc_pos, tpc_Z_pos, tpcmod_dx1, tpcmod_dx2, tpcmod_dy,
     >   tpcmod_dz, Rch, Rptc, ddr, dx_add, pi_4, pi_8,
     >   dr_mlrth, dz_mlrth, dr_gap, dz_gap
	 Integer nmpadrow
