/*:>--------------------------------------------------------------------
**: FILE:       mTofSetFEMmap.c.template
**: HISTORY:
**:             00jan93-v000a-hpl- Created by stic Version
**: 
**:             10/20/98 H. Sako   Set nok to 960
**:             10/23/98 H. Sako   changed exit(1) to return STAFCV_BAD
**:             07/22/99 A. Kiyomichi   fix slatid info.
**:             05/17/00 A. Kiyomichi   add return value in check_map
**:             06/11/00 A. Kiyomichi   remove tof_common.h
**:
**:  Id: idl.y,v 1.11 1998/06/23 15:52:43 ward Exp  
**:<------------------------------------------------------------------*/
#include "mTofSetFEMmap.h"
#include "emlLib.h"
#include <stdio.h>

#define PANEL_DEBUG 11

#define NO_CHECK_MAP

#ifndef NO_CHECK_MAP
static short find_slatid(TABLE_HEAD_ST *dTofFEMmap_h,
			 DTOFFEMMAP_ST *dTofFEMmap,
			 short crate, short slot, short ch, short *tb) {
  short slatid;
  *tb = -1;
  for (slatid = 0; slatid < dTofFEMmap_h->nok; slatid++) {
    DTOFFEMMAP_ST *map = &dTofFEMmap[slatid];
    if ((map->crate == crate) && (map->slot == slot)) {
      if (map->ch[0] == ch) {
	*tb = 0;
	break;
      }
      else if (map->ch[1] == ch) {
	*tb = 1;
	break;
      }
    }
  } /* end of slatid loop */
  if (*tb != -1)
    return slatid;
  else
    return -1;
}

static int check_map (TABLE_HEAD_ST *dTofFEMmap_h, DTOFFEMMAP_ST *dTofFEMmap) {
  short slatid, icrate, islot, ich;
  short tb;

  for (icrate = 0; icrate < 8; icrate++) {
    for (islot = 0; islot < 16; islot++) {
      for (ich=0;ich<16; ich++) {
	slatid = find_slatid(dTofFEMmap_h, dTofFEMmap,
			     icrate, islot, ich, &tb);
	if (slatid == -1)
	  printf("crate %d, slot %d, ch %d --- slatid %d, tb %d\n",
		 icrate, islot, ich, slatid, tb);
      }
    }
  }
  return 1;
}
#endif

long mTofSetFEMmap_(
  TABLE_HEAD_ST        *dTofGeo_h,        DTOFGEO_ST          *dTofGeo ,
  TABLE_HEAD_ST     *dTofFEMmap_h,     DTOFFEMMAP_ST       *dTofFEMmap )
{
/*:>--------------------------------------------------------------------
**: ROUTINE:    mTofSetFEMmap_
**: DESCRIPTION: Physics Analysis Module ANSI C template.
**:             This is an ANSI C Physics Analysis Module template
**:             automatically generated by stic from mTofSetFEMmap.idl.
**:             Please edit comments and code.
**: AUTHOR:     hpl - H.P. Lovecraft, hplovecraft@cthulhu.void
**: ARGUMENTS:
**:       IN:
**:            dTofGeo    - PLEASE FILL IN DESCRIPTION HERE
**:           dTofGeo_h   - header Structure for dTofGeo
**:    INOUT:
**:      OUT:
**:         dTofFEMmap    - PLEASE FILL IN DESCRIPTION HERE
**:        dTofFEMmap_h   - header Structure for dTofFEMmap
**: RETURNS:    STAF Condition Value
**:>------------------------------------------------------------------*/

  short slatid; /*Slatid index */
  short sector, side, panel, slat; 
  short panel_seq = 0;
  const int nslat = 96;
  const int nFEMch = 16;


  /* Set nok to 960 */
  dTofFEMmap_h->nok = nslat*10;

/* Sanity check of header for table "dTofFEMmap"... */
    if( ( dTofFEMmap_h->maxlen <= 0 ) ||
       ( dTofFEMmap_h->nok > dTofFEMmap_h->maxlen ) ){
       return STAFCV_BAD;
    }

/* Show data of long scalar column "sss" of table "dTofFEMmap"... */
    for (slatid=0;slatid< nslat*10; slatid++) {

      sector = dTofGeo[slatid].sector;
      side   = dTofGeo[slatid].side;
      panel  = dTofGeo[slatid].panel;
      slat   = dTofGeo[slatid].slat;
      
      /*
panel   3 2 1 0 0 1 2 3   Sector
	I H G F D C B A     1

              J E           0

   side:   1       0

   panel_seq = 0 1 2 3 4 5 6 7 8 9
               A B C D E F G H I J
       */

      
      if (sector == 1) {
	if (side == 0) {
	  if (panel == 3) 
	    panel_seq = 0; /* Panel A */
	  else if (panel == 2)
	    panel_seq = 1; /* Panel B */
	  else if (panel == 1)
	    panel_seq = 2; /* Panel C */
	  else if (panel == 0)
	    panel_seq = 3; /* Panel D */
	  else {
	    printf("Strange panel = %d\n", panel);
	    return STAFCV_BAD;
	    /* strange panel */
	  }
	}
	else if (side == 1) {
	  if (panel == 0)
	    panel_seq = 5; /* Panel F */
	  else if (panel == 1)
	    panel_seq = 6; /* Panel G */
	  else if (panel == 2)
	    panel_seq = 7; /* Panel H */
	  else if (panel == 3)
	    panel_seq = 8; /* Panel I */
	  else {
	    printf("Strange panel = %d\n", panel);
	    return STAFCV_BAD;
	    /* strange panel */
	  }
	}
	else { /* Strange side */
	  printf("Strange side = %d\n", side);
	  return STAFCV_BAD;
	}
      }
      else if (sector == 0) {
	if (side == 0) {
	  if (panel == 0)
	    panel_seq = 4; /* Panel E */
	  else {
	    printf("Strange sector/side/panel = %d/%d/%d\n",
		   sector, side, panel);
	    return STAFCV_BAD;
	  }
	}
	else if (side == 1) {
	  if (panel == 0)
	    panel_seq = 9; /* Panel J */
	  else {
	    printf("Strange sector/side/panel = %d/%d/%d\n",
		   sector, side, panel);
	    return STAFCV_BAD;
	  }	    
	}
      }

      dTofFEMmap[slatid].slatid = slatid;    /* Add 07/22/99 -AK */

      if (panel_seq == 4) {/* Panel E */
	dTofFEMmap[slatid].crate = 3;
	dTofFEMmap[slatid].slot  = slat/(nFEMch/2);
	dTofFEMmap[slatid].ch[0] = slat%(nFEMch/2)*2+1; /*bottom PMT*/
	dTofFEMmap[slatid].ch[1] = slat%(nFEMch/2)*2;   /*top PMT*/
	    
	if (panel_seq == PANEL_DEBUG) {
	  printf("\n");
	  printf(" sector, side, panel, slat = %d,%d,%d,%d\n",
		 sector, side, panel, slat);
	  printf(" crate, slot = %d,%d\n",dTofFEMmap[slatid].crate,
		 dTofFEMmap[slatid].slot);
	  printf(" ch[0],ch[1] = %d,%d\n",dTofFEMmap[slatid].ch[0],
		 dTofFEMmap[slatid].ch[1]);
	}  
	continue; /* Go to next slatid */
      } else if (panel_seq == 9) { /* Panel J */
	dTofFEMmap[slatid].crate = 7;
	dTofFEMmap[slatid].slot  = 15-slat/(nFEMch/2);
	dTofFEMmap[slatid].ch[0] = slat%(nFEMch/2)*2+1; /*bottom PMT*/
	dTofFEMmap[slatid].ch[1] = slat%(nFEMch/2)*2;   /*top PMT*/
	
	if (panel_seq == PANEL_DEBUG) {
	  printf("\n");
	  printf(" sector, side, panel, slat = %d,%d,%d,%d\n",
		 sector, side, panel, slat);
	  printf(" crate, slot = %d,%d\n",dTofFEMmap[slatid].crate,
		 dTofFEMmap[slatid].slot);
	  printf(" ch[0],ch[1] = %d,%d\n",dTofFEMmap[slatid].ch[0],
		 dTofFEMmap[slatid].ch[1]);
	}
	continue;  /* Go to next slatid */
      }

      /* Other than Panles E and K */
      if (slat < 32) {
	  switch (panel_seq) {
	  case 0: /* Panel A */
	    dTofFEMmap[slatid].crate = 2;
	    dTofFEMmap[slatid].slot  = 3 - slat/(nFEMch/2);
	    break;
	  case 1: /* Panel B */
	    dTofFEMmap[slatid].crate = 2;
	    dTofFEMmap[slatid].slot  = 7 - slat/(nFEMch/2);
	    break;
	  case 2: /* Panel C */
	    dTofFEMmap[slatid].crate = 2;
	    dTofFEMmap[slatid].slot  = 11 - slat/(nFEMch/2);
	    break;
	  case 3: /* Panel D */
	    dTofFEMmap[slatid].crate = 2;
	    dTofFEMmap[slatid].slot  = 15 - slat/(nFEMch/2);
	    break;
	  case 5: /* Panel F <-> D */
	    dTofFEMmap[slatid].crate = 6;
	    dTofFEMmap[slatid].slot  = slat/(nFEMch/2);	    
	    break;
	  case 6: /* Panel G <-> C */
	    dTofFEMmap[slatid].crate = 6;
	    dTofFEMmap[slatid].slot  = 4 + slat/(nFEMch/2);
	    break;
	  case 7: /* Panel H <-> B */
	    dTofFEMmap[slatid].crate = 6;
	    dTofFEMmap[slatid].slot  = 8 + slat/(nFEMch/2);
	    break;
	  case 8: /* Panel I <-> A */
 	    dTofFEMmap[slatid].crate = 6;
	    dTofFEMmap[slatid].slot  = 12 + slat/(nFEMch/2);
	    break; 
	  default:
	    printf("strange Panel (in mTofSetFEMmap = %d\n", panel_seq);
	    return STAFCV_BAD;
	    break;
	  }
	  if (slat >= 16) {
	    dTofFEMmap[slatid].ch[0] = (slat%(nFEMch/2))*2+1; /*bottom PMT*/
	    dTofFEMmap[slatid].ch[1] = (slat%(nFEMch/2))*2;   /*top PMT*/ }
	  else {
	    dTofFEMmap[slatid].ch[0] = 15-((slat%(nFEMch/2))*2);
	    /*bottom PMT*/
	    dTofFEMmap[slatid].ch[1] = 15-((slat%(nFEMch/2))*2+1);
	    /*top PMT*/ }
	} else { /* slat>=32 */
	  switch (panel_seq) {
	  case 0: /* Panel A */
	    dTofFEMmap[slatid].crate = 1;
	    dTofFEMmap[slatid].slot  = slat/(nFEMch/2) - 4;
	    break;
	  case 1: /* Panel B */
	    dTofFEMmap[slatid].crate = 1;
	    dTofFEMmap[slatid].slot  = slat/(nFEMch/2) + 4;
	    break;
	  case 2: /* Panel C */
	    dTofFEMmap[slatid].crate = 0;
	    dTofFEMmap[slatid].slot  = slat/(nFEMch/2) - 4;
	    break;
	  case 3: /* Panel D */
	    dTofFEMmap[slatid].crate = 0;
	    dTofFEMmap[slatid].slot  = slat/(nFEMch/2) + 4;
	    break;
	  case 5: /* Panel F <-> D */
	    dTofFEMmap[slatid].crate = 4;
	    dTofFEMmap[slatid].slot  = 11 - slat/(nFEMch/2);
	    break;
	  case 6: /* Panel G <-> C */
	    dTofFEMmap[slatid].crate = 4;
	    dTofFEMmap[slatid].slot  = 19 - slat/(nFEMch/2);
	    break;
	  case 7: /* Panel H <-> B */
	    dTofFEMmap[slatid].crate = 5;
	    dTofFEMmap[slatid].slot  = 11 - slat/(nFEMch/2);
	    break;
	  case 8: /* Panel I <-> A */
	    dTofFEMmap[slatid].crate = 5;
	    dTofFEMmap[slatid].slot  = 19 - slat/(nFEMch/2);
	    break;	    
	  default:
	    printf("strange Panel (in mTofSetFEMmap = %d\n", panel_seq);
	    return STAFCV_BAD;
	    break;
	  }
	  if ((64 <= slat) && (slat < 80)) {
	    dTofFEMmap[slatid].ch[0] = 15-((slat%(nFEMch/2))*2);
	    /*bottom PMT*/
	    dTofFEMmap[slatid].ch[1] = 15-((slat%(nFEMch/2))*2+1);
	    /*top PMT*/ }	    
	  else {
	    dTofFEMmap[slatid].ch[0] = (slat%(nFEMch/2))*2+1; /*bottom PMT*/
	    dTofFEMmap[slatid].ch[1] = (slat%(nFEMch/2))*2;   /*top PMT*/
	  }
	}
	    
      if (panel_seq == PANEL_DEBUG) {
	printf("\n");
	printf(" sector, side, panel, slat = %d,%d,%d,%d\n",
		 sector, side, panel, slat);
        printf(" crate, slot = %d,%d\n",dTofFEMmap[slatid].crate,
	       dTofFEMmap[slatid].slot);
        printf(" ch[0],ch[1] = %d,%d\n",dTofFEMmap[slatid].ch[0],
	       dTofFEMmap[slatid].ch[1]);
	}

      }

#ifdef CHECK_MAP
  check_map(dTofFEMmap_h, dTofFEMmap);
#endif
    
  return STAFCV_OK;

}

#ifndef NO_CHECK_MAP

#endif
