{

//Declaration of leaves types
   Float_t         IPAIR;
   Float_t         ICGL1;
   Float_t         PTOT1;
   Float_t         PTHETA1;
   Float_t         PPHI1;
   Float_t         DCQUAL1;
   Float_t         DCALPHA1;
   Float_t         NFILE1;
   Float_t         DSG1ZPC2;
   Float_t         DSG1PPC2;
   Float_t         DSG1ZPC3;
   Float_t         DSG1PPC3;
   Float_t         DSG1ZTOF;
   Float_t         DSG1PTOF;
   Float_t         MCIDPAR1;
   Float_t         RECMASS1;
   Float_t         MCTOF1;
   Float_t         RECOTOF1;
   Float_t         PC3PHI1;
   Float_t         PC3THETA1;
   Float_t         PC1PRNT1;
   Float_t         PC3PRNT1;
   Float_t         DCHZED1;
   Float_t         DCHPHI1;
   Float_t         PCDOM1;
   Float_t         PTOTVERT1;
   Float_t         ANGERR1;
   Float_t         RVERT1;
   Float_t         ZVERT1;
   Float_t         ISKAON1;
   Float_t         TOFDELE1;
   Float_t         DSGZEMC1;
   Float_t         DSGPEMC1;
   Float_t         EMCTCOR1;
   Float_t         EMCMASS1;
   Float_t         ICGL2;
   Float_t         PTOT2;
   Float_t         PTHETA2;
   Float_t         PPHI2;
   Float_t         DCQUAL2;
   Float_t         DCALPHA2;
   Float_t         NFILE2;
   Float_t         DSG2ZPC2;
   Float_t         DSG2PPC2;
   Float_t         DSG2ZPC3;
   Float_t         DSG2PPC3;
   Float_t         DSG2ZTOF;
   Float_t         DSG2PTOF;
   Float_t         MCIDPAR2;
   Float_t         RECMASS2;
   Float_t         MCTOF2;
   Float_t         RECOTOF2;
   Float_t         PC3PHI2;
   Float_t         PC3THETA2;
   Float_t         PC1PRNT2;
   Float_t         PC3PRNT2;
   Float_t         DCHZED2;
   Float_t         DCHPHI2;
   Float_t         PCDOM2;
   Float_t         PTOTVERT2;
   Float_t         ANGERR2;
   Float_t         RVERT2;
   Float_t         ZVERT2;
   Float_t         ISKAON2;
   Float_t         TOFDELE2;
   Float_t         DSGZEMC2;
   Float_t         DSGPEMC2;
   Float_t         EMCTCOR2;
   Float_t         EMCMASS2;
   Float_t         PAIRMASS;
   Float_t         PAIRPTRAN;
   Float_t         PAIRPTOT;
   Float_t         PAIRTHET;
   Float_t         PAIRPHI;
   Float_t         VERTMASS;
   Float_t         MASSKK;
   Float_t         VERTPTRAN;
   Float_t         MASSKK01;
   Float_t         OPENANGLE;
   Float_t         OPENRECO;
   Float_t         NPAIRS;
   Float_t         VTXOUTT0;
   Float_t         VTXOUTZ0;
   Float_t         BBCTZERO;
   Float_t         NDCTRACK;
   Float_t         NPC1CLUS;
   Float_t         NPC2CLUS;
   Float_t         NPC3CLUS;
   Float_t         NTCTRACK;
   Float_t         BBCNORTH;
   Float_t         BBCSOUTH;
   Float_t         BBCZVERT;
   Float_t         Z0_EVENT;
   Float_t         B_IMPACT;
   Float_t         EVENT;

   // Set branch addresses.
   CglPair->SetBranchAddress("IPAIR",&IPAIR);
   CglPair->SetBranchAddress("ICGL1",&ICGL1);
   CglPair->SetBranchAddress("PTOT1",&PTOT1);
   CglPair->SetBranchAddress("PTHETA1",&PTHETA1);
   CglPair->SetBranchAddress("PPHI1",&PPHI1);
   CglPair->SetBranchAddress("DCQUAL1",&DCQUAL1);
   CglPair->SetBranchAddress("DCALPHA1",&DCALPHA1);
   CglPair->SetBranchAddress("NFILE1",&NFILE1);
   CglPair->SetBranchAddress("DSG1ZPC2",&DSG1ZPC2);
   CglPair->SetBranchAddress("DSG1PPC2",&DSG1PPC2);
   CglPair->SetBranchAddress("DSG1ZPC3",&DSG1ZPC3);
   CglPair->SetBranchAddress("DSG1PPC3",&DSG1PPC3);
   CglPair->SetBranchAddress("DSG1ZTOF",&DSG1ZTOF);
   CglPair->SetBranchAddress("DSG1PTOF",&DSG1PTOF);
   CglPair->SetBranchAddress("MCIDPAR1",&MCIDPAR1);
   CglPair->SetBranchAddress("RECMASS1",&RECMASS1);
   CglPair->SetBranchAddress("MCTOF1",&MCTOF1);
   CglPair->SetBranchAddress("RECOTOF1",&RECOTOF1);
   CglPair->SetBranchAddress("PC3PHI1",&PC3PHI1);
   CglPair->SetBranchAddress("PC3THETA1",&PC3THETA1);
   CglPair->SetBranchAddress("PC1PRNT1",&PC1PRNT1);
   CglPair->SetBranchAddress("PC3PRNT1",&PC3PRNT1);
   CglPair->SetBranchAddress("DCHZED1",&DCHZED1);
   CglPair->SetBranchAddress("DCHPHI1",&DCHPHI1);
   CglPair->SetBranchAddress("PCDOM1",&PCDOM1);
   CglPair->SetBranchAddress("PTOTVERT1",&PTOTVERT1);
   CglPair->SetBranchAddress("ANGERR1",&ANGERR1);
   CglPair->SetBranchAddress("RVERT1",&RVERT1);
   CglPair->SetBranchAddress("ZVERT1",&ZVERT1);
   CglPair->SetBranchAddress("ISKAON1",&ISKAON1);
   CglPair->SetBranchAddress("TOFDELE1",&TOFDELE1);
   CglPair->SetBranchAddress("DSGZEMC1",&DSGZEMC1);
   CglPair->SetBranchAddress("DSGPEMC1",&DSGPEMC1);
   CglPair->SetBranchAddress("EMCTCOR1",&EMCTCOR1);
   CglPair->SetBranchAddress("EMCMASS1",&EMCMASS1);
   CglPair->SetBranchAddress("ICGL2",&ICGL2);
   CglPair->SetBranchAddress("PTOT2",&PTOT2);
   CglPair->SetBranchAddress("PTHETA2",&PTHETA2);
   CglPair->SetBranchAddress("PPHI2",&PPHI2);
   CglPair->SetBranchAddress("DCQUAL2",&DCQUAL2);
   CglPair->SetBranchAddress("DCALPHA2",&DCALPHA2);
   CglPair->SetBranchAddress("NFILE2",&NFILE2);
   CglPair->SetBranchAddress("DSG2ZPC2",&DSG2ZPC2);
   CglPair->SetBranchAddress("DSG2PPC2",&DSG2PPC2);
   CglPair->SetBranchAddress("DSG2ZPC3",&DSG2ZPC3);
   CglPair->SetBranchAddress("DSG2PPC3",&DSG2PPC3);
   CglPair->SetBranchAddress("DSG2ZTOF",&DSG2ZTOF);
   CglPair->SetBranchAddress("DSG2PTOF",&DSG2PTOF);
   CglPair->SetBranchAddress("MCIDPAR2",&MCIDPAR2);
   CglPair->SetBranchAddress("RECMASS2",&RECMASS2);
   CglPair->SetBranchAddress("MCTOF2",&MCTOF2);
   CglPair->SetBranchAddress("RECOTOF2",&RECOTOF2);
   CglPair->SetBranchAddress("PC3PHI2",&PC3PHI2);
   CglPair->SetBranchAddress("PC3THETA2",&PC3THETA2);
   CglPair->SetBranchAddress("PC1PRNT2",&PC1PRNT2);
   CglPair->SetBranchAddress("PC3PRNT2",&PC3PRNT2);
   CglPair->SetBranchAddress("DCHZED2",&DCHZED2);
   CglPair->SetBranchAddress("DCHPHI2",&DCHPHI2);
   CglPair->SetBranchAddress("PCDOM2",&PCDOM2);
   CglPair->SetBranchAddress("PTOTVERT2",&PTOTVERT2);
   CglPair->SetBranchAddress("ANGERR2",&ANGERR2);
   CglPair->SetBranchAddress("RVERT2",&RVERT2);
   CglPair->SetBranchAddress("ZVERT2",&ZVERT2);
   CglPair->SetBranchAddress("ISKAON2",&ISKAON2);
   CglPair->SetBranchAddress("TOFDELE2",&TOFDELE2);
   CglPair->SetBranchAddress("DSGZEMC2",&DSGZEMC2);
   CglPair->SetBranchAddress("DSGPEMC2",&DSGPEMC2);
   CglPair->SetBranchAddress("EMCTCOR2",&EMCTCOR2);
   CglPair->SetBranchAddress("EMCMASS2",&EMCMASS2);
   CglPair->SetBranchAddress("PAIRMASS",&PAIRMASS);
   CglPair->SetBranchAddress("PAIRPTRAN",&PAIRPTRAN);
   CglPair->SetBranchAddress("PAIRPTOT",&PAIRPTOT);
   CglPair->SetBranchAddress("PAIRTHET",&PAIRTHET);
   CglPair->SetBranchAddress("PAIRPHI",&PAIRPHI);
   CglPair->SetBranchAddress("VERTMASS",&VERTMASS);
   CglPair->SetBranchAddress("MASSKK",&MASSKK);
   CglPair->SetBranchAddress("VERTPTRAN",&VERTPTRAN);
   CglPair->SetBranchAddress("MASSKK01",&MASSKK01);
   CglPair->SetBranchAddress("OPENANGLE",&OPENANGLE);
   CglPair->SetBranchAddress("OPENRECO",&OPENRECO);
   CglPair->SetBranchAddress("NPAIRS",&NPAIRS);
   CglPair->SetBranchAddress("VTXOUTT0",&VTXOUTT0);
   CglPair->SetBranchAddress("VTXOUTZ0",&VTXOUTZ0);
   CglPair->SetBranchAddress("BBCTZERO",&BBCTZERO);
   CglPair->SetBranchAddress("NDCTRACK",&NDCTRACK);
   CglPair->SetBranchAddress("NPC1CLUS",&NPC1CLUS);
   CglPair->SetBranchAddress("NPC2CLUS",&NPC2CLUS);
   CglPair->SetBranchAddress("NPC3CLUS",&NPC3CLUS);
   CglPair->SetBranchAddress("NTCTRACK",&NTCTRACK);
   CglPair->SetBranchAddress("BBCNORTH",&BBCNORTH);
   CglPair->SetBranchAddress("BBCSOUTH",&BBCSOUTH);
   CglPair->SetBranchAddress("BBCZVERT",&BBCZVERT);
   CglPair->SetBranchAddress("Z0_EVENT",&Z0_EVENT);
   CglPair->SetBranchAddress("B_IMPACT",&B_IMPACT);
   CglPair->SetBranchAddress("EVENT",&EVENT);

}
