#! /bin/tcsh -f
#PBS -o /scratch/maguire/0/project88/dstEvents/PosField/rndm01/log90201.out
#PBS -j oe
#PBS -l walltime=0:50:00
#PBS -l cput=0:40:30
#PBS -l nodes=1:ppn=1:x86
#PBS -l mem=450mb
cd /scratch/maguire/0/project88/dstEvents/PosField/rndm01
date
echo $HOST
echo $HOST > accreHost90201
df -k /tmp
ls -al /tmp
rm -rf /tmp/maguire90201
mkdir /tmp/maguire90201
# 
# Logic to allow only one PISAEvent.root file copy at a time
# 
@ notdone = 1
@ counter = 0
while ( $notdone == 1 )
  sleep 23
  if( $counter >= 156) then
    break
  endif
  if( -e "/scratch/maguire/0/project88/dstEvents/PosField/copyPISA/copyPISAFlag") then
    @ notdone = 1
  else
    touch /scratch/maguire/0/project88/dstEvents/PosField/copyPISA/copyPISAFlag
    @ notdone = 0
    break;
  endif
  @ counter++
end
echo " "
echo "Wait counter is $counter"
echo " "
touch /scratch/maguire/0/project88/dstEvents/PosField/copyPISA/startCopy90201
cp /scratch/maguire/0/project88/pisaEvents/PosField/doneTest/PISA2000_HijingPLPL-0000090201-0088.rootg /tmp/maguire90201/PISAEvent.root
cp AlwaysDeadCh_pp200_168676.dat /tmp/maguire90201
cp crk_cabling_vrdc.txt /tmp/maguire90201
cp DchEfficiency_pp200.Real /tmp/maguire90201
cp DchGeometry.frame00NoRetracted /tmp/maguire90201
cp DchGeometry.info /tmp/maguire90201
cp DchGeometry.wireMc /tmp/maguire90201
cp fieldIntegral.dat /tmp/maguire90201
cp pisaToDST.C /tmp/maguire90201
cp pisaToDST_IOManager.C /tmp/maguire90201
cp pisaToDST.input /tmp/maguire90201
touch /scratch/maguire/0/project88/dstEvents/PosField/copyPISA/endCopy90201
rm /scratch/maguire/0/project88/dstEvents/PosField/copyPISA/copyPISAFlag
cd /tmp/maguire90201
ls -al
date
root -b < pisaToDST.input >& pisaToDST90201.out
date
cd /scratch/maguire/0/project88/dstEvents/PosField/rndm01
cp /tmp/maguire90201/pisaToDST90201.out .
cp /tmp/maguire90201/simDST.root .
cp /tmp/maguire90201/simCNT.root .
cp /tmp/maguire90201/simHWG.root .
chmod u-w simCNT.root
mv simCNT.root CNT2000_HijingPLPL-0000090201-0088.rootg
mv CNT2000_HijingPLPL-0000090201-0088.rootg ../done
chmod u-w simHWG.root
mv simHWG.root HWG2000_HijingPLPL-0000090201-0088.rootg
mv HWG2000_HijingPLPL-0000090201-0088.rootg ../done
chmod u-w simDST.root
mv simDST.root DST2000_HijingPLPL-0000090201-0088.rootg
mv DST2000_HijingPLPL-0000090201-0088.rootg ../done
touch finish90201
rm -rf /tmp/maguire90201
ls -al /tmp
date
