*CMZ :  2.04/00 05/10/92  11.19.41  by  Charles F. Maguire
*-- Author :
*-- Author : V. Dzhordzhadze 07.19.2004 add NCC
      SUBROUTINE GETPARS(READNXT,NUH,IUHEAD)
C  loop through requested detectors to see if this bank belongs to one.
C  If so, read in the banks
      IMPLICIT NONE
      LOGICAL READNXT
      INTEGER NUH,IUHEAD(*), U_CTOH4
C  loop thru detector SETS names
      IF(IUHEAD(3) .EQ. U_CTOH4('CRK '))THEN
        CALL FC_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('EMC '))THEN
        CALL FE_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('INR '))THEN
        CALL FD_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('SINR'))THEN
        CALL FD_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('ITR '))THEN
        CALL FI_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('ITR '))THEN
        CALL FI_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('MUM '))THEN
        CALL FM_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('MUN '))THEN
        CALL FN_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('TOF '))THEN
        CALL FF_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('VER '))THEN
        CALL FV_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('MUPC '))THEN
        CALL Fmupc_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('RLT '))THEN
         CALL FRLT_GET_DST(READNXT,NUH,IUHEAD)
      ELSE IF(IUHEAD(3) .EQ. U_CTOH4('NCC '))THEN
         CALL FNCC_GET_DST(READNXT,NUH,IUHEAD)   
      ELSE
        WRITE(6,'(A,A)')' GETPARS:Unknown bank ',IUHEAD(3)
      END IF
      RETURN
      END
