void run_qa_prdf(char *prdffile = "data.prdf", char *outhisto="qa.root", int Nevents = 100000)
{
	gSystem->Load("libfun4all.so");
  gSystem->Load("libdstqa.so");
  Fun4AllServer *se = Fun4AllServer::instance();
  se->Verbosity(0);
  recoConsts *rc = recoConsts::instance();
  rc->set_IntFlag("PPFLAG", 1);
  rc->set_IntFlag("BFIELDFLAG", 1);
  SubsysReco *head = new HeadReco();
  SubsysReco *trig = new TrigReco();
  SubsysReco *bbc = new BbcReco();
  SubsysReco *zdc = new ZdcReco();
  SubsysReco *ntcp = new NtcpReco();
  SubsysReco *t0 = new T0Reco();
	SubsysReco *fcal = new FcalReco("FCAL");
  SubsysReco *pad = new PadReco("PAD");
  SubsysReco *vtx = new VtxReco("VTX1");
  SubsysReco *tec = new TecReco();
  SubsysReco *tof = new TofReco();
  SubsysReco *dch = new DchReco();
  SubsysReco *crk = new CrkReco();
  SubsysReco *emc = new EmcReco3();
  SubsysReco *ert = new ErtReco();
  SubsysReco *cgl = new CglReco();
  SubsysReco *ring = new RingReco("RING");
  SubsysReco *kal = new KalFitReco();
	SubsysReco *qa = new QAReco(outhisto,"ZBNSVDPTFECMRmin_bias");

  SubsysReco *mui = new MuiReco();
  //SubsysReco *mutoo = new MutooReco();
  se->registerSubsystem(head);
  se->registerSubsystem(trig);
  se->registerSubsystem(bbc);
  se->registerSubsystem(zdc);
  se->registerSubsystem(ntcp);
  se->registerSubsystem(t0);
	//  se->registerSubsystem(fcal);
  se->registerSubsystem(pad);
  se->registerSubsystem(vtx);
  se->registerSubsystem(tec);
  se->registerSubsystem(tof);
  se->registerSubsystem(dch);
  se->registerSubsystem(crk);
  se->registerSubsystem(emc);
  se->registerSubsystem(ert);
  se->registerSubsystem(cgl);
  se->registerSubsystem(ring);
  se->registerSubsystem(kal);
  se->registerSubsystem(mui);
	se->registerSubsystem(qa);
  //se->registerSubsystem(mutoo);
  se->Verbosity(0);
	iomanager("dst.proot");  // to produce DSTs
  pfileopen(prdffile);
  //gBenchmark->Start("preco");
  prun(Nevents);
  //gBenchmark->Show("preco");
  se->EndRun();
}

void iomanager(const char *outfile ="dst.root" )
{
  Fun4AllServer *se = Fun4AllServer::instance();
  Fun4AllIOManager *io = new Fun4AllIOManager("DSTOUT", outfile);
  io->AddNode("BbcOut");
  io->AddNode("BbcRaw");
  io->AddNode("CglTrack");
  io->AddNode("CglTrackBack");
  io->AddNode("CrkHit");
  io->AddNode("CrkRing");
  io->AddNode("CrkRingBack");
  io->AddNode("DchHitLineTable");
  io->AddNode("DchTrack");
  io->AddNode("dCrkHit");
  io->AddNode("dMuiPseudoTriggerOut");
  io->AddNode("dMuiRaw");
  io->AddNode("dMuiRoadRawRel");
  io->AddNode("dMutCalibCathodesOut");
  io->AddNode("dMutCathodeClusters");
  io->AddNode("dMuiClusters");
  io->AddNode("dMuiClusterRawRel");
  io->AddNode("dMuiRoads");
  io->AddNode("dMuiRoadClusterRel");
  io->AddNode("dMutSortedAnodes");
  io->AddNode("dMuoTracksOut");
  io->AddNode("dMuoTracks");
  io->AddNode("dMuoTrackRoadRel");
  io->AddNode("dPc1Cluster");
  io->AddNode("dPc2Cluster");
  io->AddNode("dPc3Cluster");
  io->AddNode("dPHDchTrack");
  io->AddNode("dTofReconstructed");
  io->AddNode("emcClusterContainer");
  io->AddNode("emcTowerContainer");
  //  io->AddNode("dEmcClusterLocalExt");
  //io->AddNode("dEmcCalibTower");
  io->AddNode("EventHeader");
  io->AddNode("ErtOut");
  io->AddNode("fclRawNorth");
  io->AddNode("fclRawSouth");
  io->AddNode("KalFitOut");
  io->AddNode("NtcpRaw");
  io->AddNode("Pc1Cluster");
  io->AddNode("Pc2Cluster");
  io->AddNode("Pc3Cluster");
  io->AddNode("PHTrackOut");
  io->AddNode("PHTrackOutBack");
  io->AddNode("PHDchTrackOut");
  io->AddNode("T0Out");
  io->AddNode("TecOut");
  io->AddNode("TofOut");
  io->AddNode("TrigLvl1");
  io->AddNode("VtxOut");
  io->AddNode("ZdcOut");
  io->AddNode("ZdcRaw");

  se->registerIOManager(io);
  io->Print();
}
