//-----------------------------------------------------------------------------
//
//  The DGO package
//  Copyright (C) PHENIX collaboration, 1999
//
//  Root LinkDef file for class reactionPlane
//
//  Author: auto-generated by PdbRootify.pl
//-----------------------------------------------------------------------------
#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class reactionPlane-!;
#pragma link C++ class utiReactionPlane+;

#endif /* __CINT__ */
